//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace CustomerPortalCMS.GeneratedModels
{
	// Mixin content Type 5209 with alias "accountPageControls"
	/// <summary>Account Page Controls</summary>
	public partial interface IAccountPageControls : IPublishedContent
	{
		/// <summary>Account Description 1</summary>
		string AccountDescription1 { get; }

		/// <summary>Account Description 2</summary>
		string AccountDescription2 { get; }

		/// <summary>Account Description 3</summary>
		string AccountDescription3 { get; }

		/// <summary>Account Heading 1</summary>
		string AccountHeading1 { get; }

		/// <summary>Account Heading 2</summary>
		string AccountHeading2 { get; }

		/// <summary>Account Heading 3</summary>
		string AccountHeading3 { get; }
	}

	/// <summary>Account Page Controls</summary>
	[PublishedContentModel("accountPageControls")]
	public partial class AccountPageControls : PublishedContentModel, IAccountPageControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "accountPageControls";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public AccountPageControls(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<AccountPageControls, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Account Description 1
		///</summary>
		[ImplementPropertyType("accountDescription1")]
		public string AccountDescription1
		{
			get { return GetAccountDescription1(this); }
		}

		/// <summary>Static getter for Account Description 1</summary>
		public static string GetAccountDescription1(IAccountPageControls that) { return that.GetPropertyValue<string>("accountDescription1"); }

		///<summary>
		/// Account Description 2
		///</summary>
		[ImplementPropertyType("accountDescription2")]
		public string AccountDescription2
		{
			get { return GetAccountDescription2(this); }
		}

		/// <summary>Static getter for Account Description 2</summary>
		public static string GetAccountDescription2(IAccountPageControls that) { return that.GetPropertyValue<string>("accountDescription2"); }

		///<summary>
		/// Account Description 3
		///</summary>
		[ImplementPropertyType("accountDescription3")]
		public string AccountDescription3
		{
			get { return GetAccountDescription3(this); }
		}

		/// <summary>Static getter for Account Description 3</summary>
		public static string GetAccountDescription3(IAccountPageControls that) { return that.GetPropertyValue<string>("accountDescription3"); }

		///<summary>
		/// Account Heading 1
		///</summary>
		[ImplementPropertyType("accountHeading1")]
		public string AccountHeading1
		{
			get { return GetAccountHeading1(this); }
		}

		/// <summary>Static getter for Account Heading 1</summary>
		public static string GetAccountHeading1(IAccountPageControls that) { return that.GetPropertyValue<string>("accountHeading1"); }

		///<summary>
		/// Account Heading 2
		///</summary>
		[ImplementPropertyType("accountHeading2")]
		public string AccountHeading2
		{
			get { return GetAccountHeading2(this); }
		}

		/// <summary>Static getter for Account Heading 2</summary>
		public static string GetAccountHeading2(IAccountPageControls that) { return that.GetPropertyValue<string>("accountHeading2"); }

		///<summary>
		/// Account Heading 3
		///</summary>
		[ImplementPropertyType("accountHeading3")]
		public string AccountHeading3
		{
			get { return GetAccountHeading3(this); }
		}

		/// <summary>Static getter for Account Heading 3</summary>
		public static string GetAccountHeading3(IAccountPageControls that) { return that.GetPropertyValue<string>("accountHeading3"); }
	}
}
