//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace CustomerPortalCMS.GeneratedModels
{
	/// <summary>Award List Control</summary>
	[PublishedContentModel("awardsListControl")]
	public partial class AwardsListControl : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "awardsListControl";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public AwardsListControl(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<AwardsListControl, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Award Location
		///</summary>
		[ImplementPropertyType("awardLocation")]
		public string AwardLocation
		{
			get { return this.GetPropertyValue<string>("awardLocation"); }
		}

		///<summary>
		/// Award Title
		///</summary>
		[ImplementPropertyType("awardTitle")]
		public string AwardTitle
		{
			get { return this.GetPropertyValue<string>("awardTitle"); }
		}

		///<summary>
		/// Award Year
		///</summary>
		[ImplementPropertyType("awardYear")]
		public string AwardYear
		{
			get { return this.GetPropertyValue<string>("awardYear"); }
		}
	}
}
