//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace CustomerPortalCMS.GeneratedModels
{
	// Mixin content Type 1277 with alias "bannerControls"
	/// <summary>Banner Controls</summary>
	public partial interface IBannerControls : IPublishedContent
	{
		/// <summary>Banner Caption</summary>
		string BannerCaption { get; }

		/// <summary>Banner Image</summary>
		IPublishedContent BannerImage { get; }

		/// <summary>Logo Over Banner</summary>
		bool LogoOverBanner { get; }
	}

	/// <summary>Banner Controls</summary>
	[PublishedContentModel("bannerControls")]
	public partial class BannerControls : PublishedContentModel, IBannerControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "bannerControls";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public BannerControls(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BannerControls, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Banner Caption: Enter a caption for this banner (optional)
		///</summary>
		[ImplementPropertyType("bannerCaption")]
		public string BannerCaption
		{
			get { return GetBannerCaption(this); }
		}

		/// <summary>Static getter for Banner Caption</summary>
		public static string GetBannerCaption(IBannerControls that) { return that.GetPropertyValue<string>("bannerCaption"); }

		///<summary>
		/// Banner Image: Choose an image for this banner
		///</summary>
		[ImplementPropertyType("bannerImage")]
		public IPublishedContent BannerImage
		{
			get { return GetBannerImage(this); }
		}

		/// <summary>Static getter for Banner Image</summary>
		public static IPublishedContent GetBannerImage(IBannerControls that) { return that.GetPropertyValue<IPublishedContent>("bannerImage"); }

		///<summary>
		/// Logo Over Banner: If this is clicked a logo will appear over the banner.
		///</summary>
		[ImplementPropertyType("logoOverBanner")]
		public bool LogoOverBanner
		{
			get { return GetLogoOverBanner(this); }
		}

		/// <summary>Static getter for Logo Over Banner</summary>
		public static bool GetLogoOverBanner(IBannerControls that) { return that.GetPropertyValue<bool>("logoOverBanner"); }
	}
}
