//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace CustomerPortalCMS.GeneratedModels
{
	// Mixin content Type 1243 with alias "bFSContactControls"
	/// <summary>BFS Contact Controls</summary>
	public partial interface IBFscontactControls : IPublishedContent
	{
		/// <summary>Support Email</summary>
		string SupportEmail { get; }

		/// <summary>Support Hours M-F</summary>
		string SupportHoursMF { get; }

		/// <summary>Support Hours Sat</summary>
		string SupportHoursSat { get; }

		/// <summary>Support Hours Sun</summary>
		string SupportHoursSun { get; }

		/// <summary>Support Phone</summary>
		string SupportPhone { get; }
	}

	/// <summary>BFS Contact Controls</summary>
	[PublishedContentModel("bFSContactControls")]
	public partial class BFscontactControls : PublishedContentModel, IBFscontactControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "bFSContactControls";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public BFscontactControls(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BFscontactControls, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Support Email
		///</summary>
		[ImplementPropertyType("supportEmail")]
		public string SupportEmail
		{
			get { return GetSupportEmail(this); }
		}

		/// <summary>Static getter for Support Email</summary>
		public static string GetSupportEmail(IBFscontactControls that) { return that.GetPropertyValue<string>("supportEmail"); }

		///<summary>
		/// Support Hours M-F
		///</summary>
		[ImplementPropertyType("supportHoursMF")]
		public string SupportHoursMF
		{
			get { return GetSupportHoursMF(this); }
		}

		/// <summary>Static getter for Support Hours M-F</summary>
		public static string GetSupportHoursMF(IBFscontactControls that) { return that.GetPropertyValue<string>("supportHoursMF"); }

		///<summary>
		/// Support Hours Sat
		///</summary>
		[ImplementPropertyType("supportHoursSat")]
		public string SupportHoursSat
		{
			get { return GetSupportHoursSat(this); }
		}

		/// <summary>Static getter for Support Hours Sat</summary>
		public static string GetSupportHoursSat(IBFscontactControls that) { return that.GetPropertyValue<string>("supportHoursSat"); }

		///<summary>
		/// Support Hours Sun
		///</summary>
		[ImplementPropertyType("supportHoursSun")]
		public string SupportHoursSun
		{
			get { return GetSupportHoursSun(this); }
		}

		/// <summary>Static getter for Support Hours Sun</summary>
		public static string GetSupportHoursSun(IBFscontactControls that) { return that.GetPropertyValue<string>("supportHoursSun"); }

		///<summary>
		/// Support Phone
		///</summary>
		[ImplementPropertyType("supportPhone")]
		public string SupportPhone
		{
			get { return GetSupportPhone(this); }
		}

		/// <summary>Static getter for Support Phone</summary>
		public static string GetSupportPhone(IBFscontactControls that) { return that.GetPropertyValue<string>("supportPhone"); }
	}
}
