//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace CustomerPortalCMS.GeneratedModels
{
	/// <summary>Bldrs Site-Map Page (copy)</summary>
	[PublishedContentModel("bldrsSiteMapPage1")]
	public partial class BldrsSiteMapPage1 : PublishedContentModel, IPageHeaderControl, ITopNavigationControl
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "bldrsSiteMapPage1";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public BldrsSiteMapPage1(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BldrsSiteMapPage1, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Tab1 Links
		///</summary>
		[ImplementPropertyType("tab1Links")]
		public IEnumerable<IPublishedContent> Tab1Links
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("tab1Links"); }
		}

		///<summary>
		/// Tab2 Link
		///</summary>
		[ImplementPropertyType("tab2Link")]
		public string Tab2Link
		{
			get { return this.GetPropertyValue<string>("tab2Link"); }
		}

		///<summary>
		/// Tab2 Links
		///</summary>
		[ImplementPropertyType("tab2Links")]
		public IEnumerable<IPublishedContent> Tab2Links
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("tab2Links"); }
		}

		///<summary>
		/// Tab2 Title
		///</summary>
		[ImplementPropertyType("tab2Title")]
		public string Tab2Title
		{
			get { return this.GetPropertyValue<string>("tab2Title"); }
		}

		///<summary>
		/// Content
		///</summary>
		[ImplementPropertyType("content")]
		public IHtmlString Content
		{
			get { return CustomerPortalCMS.GeneratedModels.PageHeaderControl.GetContent(this); }
		}

		///<summary>
		/// Header Background Image
		///</summary>
		[ImplementPropertyType("headerBackgroundImage")]
		public Umbraco.Web.Models.ImageCropDataSet HeaderBackgroundImage
		{
			get { return CustomerPortalCMS.GeneratedModels.PageHeaderControl.GetHeaderBackgroundImage(this); }
		}

		///<summary>
		/// Page Title
		///</summary>
		[ImplementPropertyType("pageTitle")]
		public string PageTitle
		{
			get { return CustomerPortalCMS.GeneratedModels.PageHeaderControl.GetPageTitle(this); }
		}

		///<summary>
		/// Hide from navigation: When checked, page will be hidden from navigation but still accessible by URL.
		///</summary>
		[ImplementPropertyType("hideFromNavigation")]
		public bool HideFromNavigation
		{
			get { return CustomerPortalCMS.GeneratedModels.TopNavigationControl.GetHideFromNavigation(this); }
		}
	}
}
