//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace CustomerPortalCMS.GeneratedModels
{
	/// <summary>Bldrs Documents Template</summary>
	[PublishedContentModel("bldrsDocumentsTemplate")]
	public partial class BldrsDocumentsTemplate : PublishedContentModel, IPageHeaderControl1, ITopNavigationControl
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "bldrsDocumentsTemplate";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public BldrsDocumentsTemplate(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BldrsDocumentsTemplate, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Documents
		///</summary>
		[ImplementPropertyType("documents")]
		public IEnumerable<IPublishedContent> Documents
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("documents"); }
		}

		///<summary>
		/// Content
		///</summary>
		[ImplementPropertyType("content")]
		public IHtmlString Content
		{
			get { return CustomerPortalCMS.GeneratedModels.PageHeaderControl1.GetContent(this); }
		}

		///<summary>
		/// Header Background Image
		///</summary>
		[ImplementPropertyType("headerBackgroundImage")]
		public Umbraco.Web.Models.ImageCropDataSet HeaderBackgroundImage
		{
			get { return CustomerPortalCMS.GeneratedModels.PageHeaderControl1.GetHeaderBackgroundImage(this); }
		}

		///<summary>
		/// Page Title
		///</summary>
		[ImplementPropertyType("pageTitle")]
		public string PageTitle
		{
			get { return CustomerPortalCMS.GeneratedModels.PageHeaderControl1.GetPageTitle(this); }
		}

		///<summary>
		/// Hide from navigation: When checked, page will be hidden from navigation but still accessible by URL.
		///</summary>
		[ImplementPropertyType("hideFromNavigation")]
		public bool HideFromNavigation
		{
			get { return CustomerPortalCMS.GeneratedModels.TopNavigationControl.GetHideFromNavigation(this); }
		}
	}
}
