//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace CustomerPortalCMS.GeneratedModels
{
	/// <summary>Bldrs Careers-WithCrop</summary>
	[PublishedContentModel("careers11")]
	public partial class Careers11 : PublishedContentModel, IBannerControls1, ICareerCarouselControls1, ICareerContentControls, ICareerIntroControls1, IHorizontalBrandsControl1, ITopNavigationControl
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "careers11";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Careers11(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Careers11, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Job Heading
		///</summary>
		[ImplementPropertyType("jobHeading")]
		public string JobHeading
		{
			get { return this.GetPropertyValue<string>("jobHeading"); }
		}

		///<summary>
		/// Banner Caption: Enter a caption for this banner (optional)
		///</summary>
		[ImplementPropertyType("bannerCaption")]
		public string BannerCaption
		{
			get { return CustomerPortalCMS.GeneratedModels.BannerControls1.GetBannerCaption(this); }
		}

		///<summary>
		/// Banner Image: Choose an image for this banner
		///</summary>
		[ImplementPropertyType("bannerImage")]
		public Umbraco.Web.Models.ImageCropDataSet BannerImage
		{
			get { return CustomerPortalCMS.GeneratedModels.BannerControls1.GetBannerImage(this); }
		}

		///<summary>
		/// Logo Over Banner: If this is clicked a logo will appear over the banner.
		///</summary>
		[ImplementPropertyType("logoOverBanner")]
		public bool LogoOverBanner
		{
			get { return CustomerPortalCMS.GeneratedModels.BannerControls1.GetLogoOverBanner(this); }
		}

		///<summary>
		/// Career Carousel Image 1: Select the image to appear first in the carousel.
		///</summary>
		[ImplementPropertyType("careerCarouselImage1")]
		public Umbraco.Web.Models.ImageCropDataSet CareerCarouselImage1
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerCarouselControls1.GetCareerCarouselImage1(this); }
		}

		///<summary>
		/// Career Carousel Image 1 Caption: Enter the caption to appear on the first carousel image
		///</summary>
		[ImplementPropertyType("careerCarouselImage1Caption")]
		public string CareerCarouselImage1Caption
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerCarouselControls1.GetCareerCarouselImage1Caption(this); }
		}

		///<summary>
		/// Career Carousel Image 2: Select the image to appear second in the carousel
		///</summary>
		[ImplementPropertyType("careerCarouselImage2")]
		public Umbraco.Web.Models.ImageCropDataSet CareerCarouselImage2
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerCarouselControls1.GetCareerCarouselImage2(this); }
		}

		///<summary>
		/// Career Carousel Image 2 Caption: Enter the caption to appear on the second carousel image
		///</summary>
		[ImplementPropertyType("careerCarouselImage2Caption")]
		public string CareerCarouselImage2Caption
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerCarouselControls1.GetCareerCarouselImage2Caption(this); }
		}

		///<summary>
		/// Career Carousel Image 3: Select the image to appear third in the carousel
		///</summary>
		[ImplementPropertyType("careerCarouselImage3")]
		public Umbraco.Web.Models.ImageCropDataSet CareerCarouselImage3
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerCarouselControls1.GetCareerCarouselImage3(this); }
		}

		///<summary>
		/// Career Carousel Image 3 Caption: Enter the caption to appear on the third carousel image
		///</summary>
		[ImplementPropertyType("careerCarouselImage3Caption")]
		public string CareerCarouselImage3Caption
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerCarouselControls1.GetCareerCarouselImage3Caption(this); }
		}

		///<summary>
		/// Career Carousel Image 4: Select the image to appear fourth in the carousel
		///</summary>
		[ImplementPropertyType("careerCarouselImage4")]
		public Umbraco.Web.Models.ImageCropDataSet CareerCarouselImage4
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerCarouselControls1.GetCareerCarouselImage4(this); }
		}

		///<summary>
		/// Career Carousel Image 4 Caption: Enter the caption to appear on the fourth carousel image
		///</summary>
		[ImplementPropertyType("careerCarouselImage4Caption")]
		public string CareerCarouselImage4Caption
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerCarouselControls1.GetCareerCarouselImage4Caption(this); }
		}

		///<summary>
		/// Career Carousel Image 5: Select the image to appear fifth in the carousel
		///</summary>
		[ImplementPropertyType("careerCarouselImage5")]
		public Umbraco.Web.Models.ImageCropDataSet CareerCarouselImage5
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerCarouselControls1.GetCareerCarouselImage5(this); }
		}

		///<summary>
		/// Career Carousel Image 5 Caption: Enter the caption to appear on the fifth carousel image.
		///</summary>
		[ImplementPropertyType("careerCarouselImage5Caption")]
		public string CareerCarouselImage5Caption
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerCarouselControls1.GetCareerCarouselImage5Caption(this); }
		}

		///<summary>
		/// Career Content
		///</summary>
		[ImplementPropertyType("careerContent")]
		public IHtmlString CareerContent
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerContentControls.GetCareerContent(this); }
		}

		///<summary>
		/// Career Intro Paragraph 1: Enter the introduction text for the first paragraph
		///</summary>
		[ImplementPropertyType("careerIntroParagraph1")]
		public IHtmlString CareerIntroParagraph1
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerIntroControls1.GetCareerIntroParagraph1(this); }
		}

		///<summary>
		/// Career Intro Paragraph 2: Enter the introduction text for the second paragraph
		///</summary>
		[ImplementPropertyType("careerIntroParagraph2")]
		public IHtmlString CareerIntroParagraph2
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerIntroControls1.GetCareerIntroParagraph2(this); }
		}

		///<summary>
		/// Career Sub Menu 1 Image: Select a image for this sub menu
		///</summary>
		[ImplementPropertyType("careerSubMenu1Image")]
		public Umbraco.Web.Models.ImageCropDataSet CareerSubMenu1Image
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerIntroControls1.GetCareerSubMenu1Image(this); }
		}

		///<summary>
		/// Career Sub Menu 1 Link: Select or enter the URL to link to
		///</summary>
		[ImplementPropertyType("careerSubMenu1Link")]
		public Umbraco.Web.Models.RelatedLinks CareerSubMenu1Link
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerIntroControls1.GetCareerSubMenu1Link(this); }
		}

		///<summary>
		/// Career Sub Menu 1 Text: Enter the text for the first sub menu image
		///</summary>
		[ImplementPropertyType("careerSubMenu1Text")]
		public string CareerSubMenu1Text
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerIntroControls1.GetCareerSubMenu1Text(this); }
		}

		///<summary>
		/// Career Sub Menu 2 Image: Select a image for this sub menu
		///</summary>
		[ImplementPropertyType("careerSubMenu2Image")]
		public Umbraco.Web.Models.ImageCropDataSet CareerSubMenu2Image
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerIntroControls1.GetCareerSubMenu2Image(this); }
		}

		///<summary>
		/// Career Sub Menu 2 Link: Select or enter the URL to link
		///</summary>
		[ImplementPropertyType("careerSubMenu2Link")]
		public Umbraco.Web.Models.RelatedLinks CareerSubMenu2Link
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerIntroControls1.GetCareerSubMenu2Link(this); }
		}

		///<summary>
		/// Career Sub Menu 2 Text: Enter the text for the second sub menu image
		///</summary>
		[ImplementPropertyType("careerSubMenu2Text")]
		public string CareerSubMenu2Text
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerIntroControls1.GetCareerSubMenu2Text(this); }
		}

		///<summary>
		/// Career Sub Menu 3 Image: Select a image for this sub menu
		///</summary>
		[ImplementPropertyType("careerSubMenu3Image")]
		public Umbraco.Web.Models.ImageCropDataSet CareerSubMenu3Image
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerIntroControls1.GetCareerSubMenu3Image(this); }
		}

		///<summary>
		/// Career Sub Menu 3 Link: Select or enter the URL to link
		///</summary>
		[ImplementPropertyType("careerSubMenu3Link")]
		public Umbraco.Web.Models.RelatedLinks CareerSubMenu3Link
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerIntroControls1.GetCareerSubMenu3Link(this); }
		}

		///<summary>
		/// Career Sub Menu 3 Text: Enter the text for the third sub menu image
		///</summary>
		[ImplementPropertyType("careerSubMenu3Text")]
		public string CareerSubMenu3Text
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerIntroControls1.GetCareerSubMenu3Text(this); }
		}

		///<summary>
		/// Career Sub Menu 4 Image: Select the image for this sub menu
		///</summary>
		[ImplementPropertyType("careerSubMenu4Image")]
		public Umbraco.Web.Models.ImageCropDataSet CareerSubMenu4Image
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerIntroControls1.GetCareerSubMenu4Image(this); }
		}

		///<summary>
		/// Career Sub Menu 4 Link: Select or enter the URL to link
		///</summary>
		[ImplementPropertyType("careerSubMenu4Link")]
		public Umbraco.Web.Models.RelatedLinks CareerSubMenu4Link
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerIntroControls1.GetCareerSubMenu4Link(this); }
		}

		///<summary>
		/// Career Sub Menu 4 Text: Enter the text for the fourth sub menu image
		///</summary>
		[ImplementPropertyType("careerSubMenu4Text")]
		public string CareerSubMenu4Text
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerIntroControls1.GetCareerSubMenu4Text(this); }
		}

		///<summary>
		/// Career Sub Menu 5 Image: Select the image for this sub menu
		///</summary>
		[ImplementPropertyType("careerSubMenu5Image")]
		public Umbraco.Web.Models.ImageCropDataSet CareerSubMenu5Image
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerIntroControls1.GetCareerSubMenu5Image(this); }
		}

		///<summary>
		/// Career Sub Menu 5 Link: Select or enter the URL to link
		///</summary>
		[ImplementPropertyType("careerSubMenu5Link")]
		public Umbraco.Web.Models.RelatedLinks CareerSubMenu5Link
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerIntroControls1.GetCareerSubMenu5Link(this); }
		}

		///<summary>
		/// Career Sub Menu 5 Text: Enter the text for the fifth sub menu image
		///</summary>
		[ImplementPropertyType("careerSubMenu5Text")]
		public string CareerSubMenu5Text
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerIntroControls1.GetCareerSubMenu5Text(this); }
		}

		///<summary>
		/// Brand Image 1: Choose a brand logo
		///</summary>
		[ImplementPropertyType("brandImage1")]
		public IPublishedContent BrandImage1
		{
			get { return CustomerPortalCMS.GeneratedModels.HorizontalBrandsControl1.GetBrandImage1(this); }
		}

		///<summary>
		/// Brand Image 2: Choose a brand logo
		///</summary>
		[ImplementPropertyType("brandImage2")]
		public IPublishedContent BrandImage2
		{
			get { return CustomerPortalCMS.GeneratedModels.HorizontalBrandsControl1.GetBrandImage2(this); }
		}

		///<summary>
		/// Brand Image 3: Choose a brand logo
		///</summary>
		[ImplementPropertyType("brandImage3")]
		public IPublishedContent BrandImage3
		{
			get { return CustomerPortalCMS.GeneratedModels.HorizontalBrandsControl1.GetBrandImage3(this); }
		}

		///<summary>
		/// Brand Image 4: Choose a brand logo
		///</summary>
		[ImplementPropertyType("brandImage4")]
		public IPublishedContent BrandImage4
		{
			get { return CustomerPortalCMS.GeneratedModels.HorizontalBrandsControl1.GetBrandImage4(this); }
		}

		///<summary>
		/// Brand Image 5: Choose a brand logo
		///</summary>
		[ImplementPropertyType("brandImage5")]
		public IPublishedContent BrandImage5
		{
			get { return CustomerPortalCMS.GeneratedModels.HorizontalBrandsControl1.GetBrandImage5(this); }
		}

		///<summary>
		/// Brand Image 6: Choose a brand logo
		///</summary>
		[ImplementPropertyType("brandImage6")]
		public IPublishedContent BrandImage6
		{
			get { return CustomerPortalCMS.GeneratedModels.HorizontalBrandsControl1.GetBrandImage6(this); }
		}

		///<summary>
		/// Brand Link 1: Choose a Link for this image (optional)
		///</summary>
		[ImplementPropertyType("brandLink1")]
		public Umbraco.Web.Models.RelatedLinks BrandLink1
		{
			get { return CustomerPortalCMS.GeneratedModels.HorizontalBrandsControl1.GetBrandLink1(this); }
		}

		///<summary>
		/// Brand Link 2: Choose a Link for this image (optional)
		///</summary>
		[ImplementPropertyType("brandLink2")]
		public Umbraco.Web.Models.RelatedLinks BrandLink2
		{
			get { return CustomerPortalCMS.GeneratedModels.HorizontalBrandsControl1.GetBrandLink2(this); }
		}

		///<summary>
		/// Brand Link 3: Choose a Link for this image (optional)
		///</summary>
		[ImplementPropertyType("brandLink3")]
		public Umbraco.Web.Models.RelatedLinks BrandLink3
		{
			get { return CustomerPortalCMS.GeneratedModels.HorizontalBrandsControl1.GetBrandLink3(this); }
		}

		///<summary>
		/// Brand Link 4: Choose a Link for this image (optional)
		///</summary>
		[ImplementPropertyType("brandLink4")]
		public Umbraco.Web.Models.RelatedLinks BrandLink4
		{
			get { return CustomerPortalCMS.GeneratedModels.HorizontalBrandsControl1.GetBrandLink4(this); }
		}

		///<summary>
		/// Brand Link 5: Choose a Link for this image (optional)
		///</summary>
		[ImplementPropertyType("brandLink5")]
		public Umbraco.Web.Models.RelatedLinks BrandLink5
		{
			get { return CustomerPortalCMS.GeneratedModels.HorizontalBrandsControl1.GetBrandLink5(this); }
		}

		///<summary>
		/// Brand Link 6: Choose a Link for this image (optional)
		///</summary>
		[ImplementPropertyType("brandLink6")]
		public Umbraco.Web.Models.RelatedLinks BrandLink6
		{
			get { return CustomerPortalCMS.GeneratedModels.HorizontalBrandsControl1.GetBrandLink6(this); }
		}

		///<summary>
		/// Hide from navigation: When checked, page will be hidden from navigation but still accessible by URL.
		///</summary>
		[ImplementPropertyType("hideFromNavigation")]
		public bool HideFromNavigation
		{
			get { return CustomerPortalCMS.GeneratedModels.TopNavigationControl.GetHideFromNavigation(this); }
		}
	}
}
