//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace CustomerPortalCMS.GeneratedModels
{
	// Mixin content Type 13083 with alias "careerCarouselControls1"
	/// <summary>Career Carousel Controls-WithCrop</summary>
	public partial interface ICareerCarouselControls1 : IPublishedContent
	{
		/// <summary>Career Carousel Image 1</summary>
		Umbraco.Web.Models.ImageCropDataSet CareerCarouselImage1 { get; }

		/// <summary>Career Carousel Image 1 Caption</summary>
		string CareerCarouselImage1Caption { get; }

		/// <summary>Career Carousel Image 2</summary>
		Umbraco.Web.Models.ImageCropDataSet CareerCarouselImage2 { get; }

		/// <summary>Career Carousel Image 2 Caption</summary>
		string CareerCarouselImage2Caption { get; }

		/// <summary>Career Carousel Image 3</summary>
		Umbraco.Web.Models.ImageCropDataSet CareerCarouselImage3 { get; }

		/// <summary>Career Carousel Image 3 Caption</summary>
		string CareerCarouselImage3Caption { get; }

		/// <summary>Career Carousel Image 4</summary>
		Umbraco.Web.Models.ImageCropDataSet CareerCarouselImage4 { get; }

		/// <summary>Career Carousel Image 4 Caption</summary>
		string CareerCarouselImage4Caption { get; }

		/// <summary>Career Carousel Image 5</summary>
		Umbraco.Web.Models.ImageCropDataSet CareerCarouselImage5 { get; }

		/// <summary>Career Carousel Image 5 Caption</summary>
		string CareerCarouselImage5Caption { get; }
	}

	/// <summary>Career Carousel Controls-WithCrop</summary>
	[PublishedContentModel("careerCarouselControls1")]
	public partial class CareerCarouselControls1 : PublishedContentModel, ICareerCarouselControls1
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "careerCarouselControls1";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public CareerCarouselControls1(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CareerCarouselControls1, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Career Carousel Image 1: Select the image to appear first in the carousel.
		///</summary>
		[ImplementPropertyType("careerCarouselImage1")]
		public Umbraco.Web.Models.ImageCropDataSet CareerCarouselImage1
		{
			get { return GetCareerCarouselImage1(this); }
		}

		/// <summary>Static getter for Career Carousel Image 1</summary>
		public static Umbraco.Web.Models.ImageCropDataSet GetCareerCarouselImage1(ICareerCarouselControls1 that) { return that.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("careerCarouselImage1"); }

		///<summary>
		/// Career Carousel Image 1 Caption: Enter the caption to appear on the first carousel image
		///</summary>
		[ImplementPropertyType("careerCarouselImage1Caption")]
		public string CareerCarouselImage1Caption
		{
			get { return GetCareerCarouselImage1Caption(this); }
		}

		/// <summary>Static getter for Career Carousel Image 1 Caption</summary>
		public static string GetCareerCarouselImage1Caption(ICareerCarouselControls1 that) { return that.GetPropertyValue<string>("careerCarouselImage1Caption"); }

		///<summary>
		/// Career Carousel Image 2: Select the image to appear second in the carousel
		///</summary>
		[ImplementPropertyType("careerCarouselImage2")]
		public Umbraco.Web.Models.ImageCropDataSet CareerCarouselImage2
		{
			get { return GetCareerCarouselImage2(this); }
		}

		/// <summary>Static getter for Career Carousel Image 2</summary>
		public static Umbraco.Web.Models.ImageCropDataSet GetCareerCarouselImage2(ICareerCarouselControls1 that) { return that.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("careerCarouselImage2"); }

		///<summary>
		/// Career Carousel Image 2 Caption: Enter the caption to appear on the second carousel image
		///</summary>
		[ImplementPropertyType("careerCarouselImage2Caption")]
		public string CareerCarouselImage2Caption
		{
			get { return GetCareerCarouselImage2Caption(this); }
		}

		/// <summary>Static getter for Career Carousel Image 2 Caption</summary>
		public static string GetCareerCarouselImage2Caption(ICareerCarouselControls1 that) { return that.GetPropertyValue<string>("careerCarouselImage2Caption"); }

		///<summary>
		/// Career Carousel Image 3: Select the image to appear third in the carousel
		///</summary>
		[ImplementPropertyType("careerCarouselImage3")]
		public Umbraco.Web.Models.ImageCropDataSet CareerCarouselImage3
		{
			get { return GetCareerCarouselImage3(this); }
		}

		/// <summary>Static getter for Career Carousel Image 3</summary>
		public static Umbraco.Web.Models.ImageCropDataSet GetCareerCarouselImage3(ICareerCarouselControls1 that) { return that.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("careerCarouselImage3"); }

		///<summary>
		/// Career Carousel Image 3 Caption: Enter the caption to appear on the third carousel image
		///</summary>
		[ImplementPropertyType("careerCarouselImage3Caption")]
		public string CareerCarouselImage3Caption
		{
			get { return GetCareerCarouselImage3Caption(this); }
		}

		/// <summary>Static getter for Career Carousel Image 3 Caption</summary>
		public static string GetCareerCarouselImage3Caption(ICareerCarouselControls1 that) { return that.GetPropertyValue<string>("careerCarouselImage3Caption"); }

		///<summary>
		/// Career Carousel Image 4: Select the image to appear fourth in the carousel
		///</summary>
		[ImplementPropertyType("careerCarouselImage4")]
		public Umbraco.Web.Models.ImageCropDataSet CareerCarouselImage4
		{
			get { return GetCareerCarouselImage4(this); }
		}

		/// <summary>Static getter for Career Carousel Image 4</summary>
		public static Umbraco.Web.Models.ImageCropDataSet GetCareerCarouselImage4(ICareerCarouselControls1 that) { return that.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("careerCarouselImage4"); }

		///<summary>
		/// Career Carousel Image 4 Caption: Enter the caption to appear on the fourth carousel image
		///</summary>
		[ImplementPropertyType("careerCarouselImage4Caption")]
		public string CareerCarouselImage4Caption
		{
			get { return GetCareerCarouselImage4Caption(this); }
		}

		/// <summary>Static getter for Career Carousel Image 4 Caption</summary>
		public static string GetCareerCarouselImage4Caption(ICareerCarouselControls1 that) { return that.GetPropertyValue<string>("careerCarouselImage4Caption"); }

		///<summary>
		/// Career Carousel Image 5: Select the image to appear fifth in the carousel
		///</summary>
		[ImplementPropertyType("careerCarouselImage5")]
		public Umbraco.Web.Models.ImageCropDataSet CareerCarouselImage5
		{
			get { return GetCareerCarouselImage5(this); }
		}

		/// <summary>Static getter for Career Carousel Image 5</summary>
		public static Umbraco.Web.Models.ImageCropDataSet GetCareerCarouselImage5(ICareerCarouselControls1 that) { return that.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("careerCarouselImage5"); }

		///<summary>
		/// Career Carousel Image 5 Caption: Enter the caption to appear on the fifth carousel image.
		///</summary>
		[ImplementPropertyType("careerCarouselImage5Caption")]
		public string CareerCarouselImage5Caption
		{
			get { return GetCareerCarouselImage5Caption(this); }
		}

		/// <summary>Static getter for Career Carousel Image 5 Caption</summary>
		public static string GetCareerCarouselImage5Caption(ICareerCarouselControls1 that) { return that.GetPropertyValue<string>("careerCarouselImage5Caption"); }
	}
}
