//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace CustomerPortalCMS.GeneratedModels
{
	/// <summary>Careers</summary>
	[PublishedContentModel("careers")]
	public partial class Careers : PublishedContentModel, IBannerControls, ICareerCarouselControls, ICareerContentControls, ICareerIntroControls, ICareersJobsCol6Controls, IHorizontalBrandsControl, ISEocontrols, ITopNavigationControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "careers";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Careers(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Careers, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Banner Caption: Enter a caption for this banner (optional)
		///</summary>
		[ImplementPropertyType("bannerCaption")]
		public string BannerCaption
		{
			get { return CustomerPortalCMS.GeneratedModels.BannerControls.GetBannerCaption(this); }
		}

		///<summary>
		/// Banner Image: Choose an image for this banner
		///</summary>
		[ImplementPropertyType("bannerImage")]
		public IPublishedContent BannerImage
		{
			get { return CustomerPortalCMS.GeneratedModels.BannerControls.GetBannerImage(this); }
		}

		///<summary>
		/// Logo Over Banner: If this is clicked a logo will appear over the banner.
		///</summary>
		[ImplementPropertyType("logoOverBanner")]
		public bool LogoOverBanner
		{
			get { return CustomerPortalCMS.GeneratedModels.BannerControls.GetLogoOverBanner(this); }
		}

		///<summary>
		/// Career Carousel Image 1: Select the image to appear first in the carousel.
		///</summary>
		[ImplementPropertyType("careerCarouselImage1")]
		public IPublishedContent CareerCarouselImage1
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerCarouselControls.GetCareerCarouselImage1(this); }
		}

		///<summary>
		/// Career Carousel Image 1 Caption: Enter the caption to appear on the first carousel image
		///</summary>
		[ImplementPropertyType("careerCarouselImage1Caption")]
		public string CareerCarouselImage1Caption
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerCarouselControls.GetCareerCarouselImage1Caption(this); }
		}

		///<summary>
		/// Career Carousel Image 2: Select the image to appear second in the carousel
		///</summary>
		[ImplementPropertyType("careerCarouselImage2")]
		public IPublishedContent CareerCarouselImage2
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerCarouselControls.GetCareerCarouselImage2(this); }
		}

		///<summary>
		/// Career Carousel Image 2 Caption: Enter the caption to appear on the second carousel image
		///</summary>
		[ImplementPropertyType("careerCarouselImage2Caption")]
		public string CareerCarouselImage2Caption
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerCarouselControls.GetCareerCarouselImage2Caption(this); }
		}

		///<summary>
		/// Career Carousel Image 3: Select the image to appear third in the carousel
		///</summary>
		[ImplementPropertyType("careerCarouselImage3")]
		public IPublishedContent CareerCarouselImage3
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerCarouselControls.GetCareerCarouselImage3(this); }
		}

		///<summary>
		/// Career Carousel Image 3 Caption: Enter the caption to appear on the third carousel image
		///</summary>
		[ImplementPropertyType("careerCarouselImage3Caption")]
		public string CareerCarouselImage3Caption
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerCarouselControls.GetCareerCarouselImage3Caption(this); }
		}

		///<summary>
		/// Career Carousel Image 4: Select the image to appear fourth in the carousel
		///</summary>
		[ImplementPropertyType("careerCarouselImage4")]
		public IPublishedContent CareerCarouselImage4
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerCarouselControls.GetCareerCarouselImage4(this); }
		}

		///<summary>
		/// Career Carousel Image 4 Caption: Enter the caption to appear on the fourth carousel image
		///</summary>
		[ImplementPropertyType("careerCarouselImage4Caption")]
		public string CareerCarouselImage4Caption
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerCarouselControls.GetCareerCarouselImage4Caption(this); }
		}

		///<summary>
		/// Career Carousel Image 5: Select the image to appear fifth in the carousel
		///</summary>
		[ImplementPropertyType("careerCarouselImage5")]
		public IPublishedContent CareerCarouselImage5
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerCarouselControls.GetCareerCarouselImage5(this); }
		}

		///<summary>
		/// Career Carousel Image 5 Caption: Enter the caption to appear on the fifth carousel image.
		///</summary>
		[ImplementPropertyType("careerCarouselImage5Caption")]
		public string CareerCarouselImage5Caption
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerCarouselControls.GetCareerCarouselImage5Caption(this); }
		}

		///<summary>
		/// Career Content
		///</summary>
		[ImplementPropertyType("careerContent")]
		public IHtmlString CareerContent
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerContentControls.GetCareerContent(this); }
		}

		///<summary>
		/// Career Intro Paragraph 1: Enter the introduction text for the first paragraph
		///</summary>
		[ImplementPropertyType("careerIntroParagraph1")]
		public IHtmlString CareerIntroParagraph1
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerIntroControls.GetCareerIntroParagraph1(this); }
		}

		///<summary>
		/// Career Intro Paragraph 2: Enter the introduction text for the second paragraph
		///</summary>
		[ImplementPropertyType("careerIntroParagraph2")]
		public IHtmlString CareerIntroParagraph2
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerIntroControls.GetCareerIntroParagraph2(this); }
		}

		///<summary>
		/// Career Sub Menu 1 Image: Select a image for this sub menu
		///</summary>
		[ImplementPropertyType("careerSubMenu1Image")]
		public IPublishedContent CareerSubMenu1Image
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerIntroControls.GetCareerSubMenu1Image(this); }
		}

		///<summary>
		/// Career Sub Menu 1 Link: Select or enter the URL to link to
		///</summary>
		[ImplementPropertyType("careerSubMenu1Link")]
		public Umbraco.Web.Models.RelatedLinks CareerSubMenu1Link
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerIntroControls.GetCareerSubMenu1Link(this); }
		}

		///<summary>
		/// Career Sub Menu 1 Text: Enter the text for the first sub menu image
		///</summary>
		[ImplementPropertyType("careerSubMenu1Text")]
		public string CareerSubMenu1Text
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerIntroControls.GetCareerSubMenu1Text(this); }
		}

		///<summary>
		/// Career Sub Menu 2 Image: Select a image for this sub menu
		///</summary>
		[ImplementPropertyType("careerSubMenu2Image")]
		public IPublishedContent CareerSubMenu2Image
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerIntroControls.GetCareerSubMenu2Image(this); }
		}

		///<summary>
		/// Career Sub Menu 2 Link: Select or enter the URL to link
		///</summary>
		[ImplementPropertyType("careerSubMenu2Link")]
		public Umbraco.Web.Models.RelatedLinks CareerSubMenu2Link
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerIntroControls.GetCareerSubMenu2Link(this); }
		}

		///<summary>
		/// Career Sub Menu 2 Text: Enter the text for the second sub menu image
		///</summary>
		[ImplementPropertyType("careerSubMenu2Text")]
		public string CareerSubMenu2Text
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerIntroControls.GetCareerSubMenu2Text(this); }
		}

		///<summary>
		/// Career Sub Menu 3 Image: Select a image for this sub menu
		///</summary>
		[ImplementPropertyType("careerSubMenu3Image")]
		public IPublishedContent CareerSubMenu3Image
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerIntroControls.GetCareerSubMenu3Image(this); }
		}

		///<summary>
		/// Career Sub Menu 3 Link: Select or enter the URL to link
		///</summary>
		[ImplementPropertyType("careerSubMenu3Link")]
		public Umbraco.Web.Models.RelatedLinks CareerSubMenu3Link
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerIntroControls.GetCareerSubMenu3Link(this); }
		}

		///<summary>
		/// Career Sub Menu 3 Text: Enter the text for the third sub menu image
		///</summary>
		[ImplementPropertyType("careerSubMenu3Text")]
		public string CareerSubMenu3Text
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerIntroControls.GetCareerSubMenu3Text(this); }
		}

		///<summary>
		/// Career Sub Menu 4 Image: Select the image for this sub menu
		///</summary>
		[ImplementPropertyType("careerSubMenu4Image")]
		public IPublishedContent CareerSubMenu4Image
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerIntroControls.GetCareerSubMenu4Image(this); }
		}

		///<summary>
		/// Career Sub Menu 4 Link: Select or enter the URL to link
		///</summary>
		[ImplementPropertyType("careerSubMenu4Link")]
		public Umbraco.Web.Models.RelatedLinks CareerSubMenu4Link
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerIntroControls.GetCareerSubMenu4Link(this); }
		}

		///<summary>
		/// Career Sub Menu 4 Text: Enter the text for the fourth sub menu image
		///</summary>
		[ImplementPropertyType("careerSubMenu4Text")]
		public string CareerSubMenu4Text
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerIntroControls.GetCareerSubMenu4Text(this); }
		}

		///<summary>
		/// Career Sub Menu 5 Image: Select the image for this sub menu
		///</summary>
		[ImplementPropertyType("careerSubMenu5Image")]
		public IPublishedContent CareerSubMenu5Image
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerIntroControls.GetCareerSubMenu5Image(this); }
		}

		///<summary>
		/// Career Sub Menu 5 Link: Select or enter the URL to link
		///</summary>
		[ImplementPropertyType("careerSubMenu5Link")]
		public Umbraco.Web.Models.RelatedLinks CareerSubMenu5Link
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerIntroControls.GetCareerSubMenu5Link(this); }
		}

		///<summary>
		/// Career Sub Menu 5 Text: Enter the text for the fifth sub menu image
		///</summary>
		[ImplementPropertyType("careerSubMenu5Text")]
		public string CareerSubMenu5Text
		{
			get { return CustomerPortalCMS.GeneratedModels.CareerIntroControls.GetCareerSubMenu5Text(this); }
		}

		///<summary>
		/// Job 1 Description: Enter a description for this position
		///</summary>
		[ImplementPropertyType("job1Description")]
		public IHtmlString Job1Description
		{
			get { return CustomerPortalCMS.GeneratedModels.CareersJobsCol6Controls.GetJob1Description(this); }
		}

		///<summary>
		/// Job 1 Image: Choose an image for this Job
		///</summary>
		[ImplementPropertyType("job1Image")]
		public IPublishedContent Job1Image
		{
			get { return CustomerPortalCMS.GeneratedModels.CareersJobsCol6Controls.GetJob1Image(this); }
		}

		///<summary>
		/// Job 1 Image Caption: Enter a caption for this image (optional)
		///</summary>
		[ImplementPropertyType("job1ImageCaption")]
		public string Job1ImageCaption
		{
			get { return CustomerPortalCMS.GeneratedModels.CareersJobsCol6Controls.GetJob1ImageCaption(this); }
		}

		///<summary>
		/// Job 1 Image Video Link
		///</summary>
		[ImplementPropertyType("job1ImageVideoLink")]
		public Umbraco.Web.Models.RelatedLinks Job1ImageVideoLink
		{
			get { return CustomerPortalCMS.GeneratedModels.CareersJobsCol6Controls.GetJob1ImageVideoLink(this); }
		}

		///<summary>
		/// Job 1 Link: Choose a URL to link to (*the link caption text will be used for the text in the button)
		///</summary>
		[ImplementPropertyType("job1Link")]
		public Umbraco.Web.Models.RelatedLinks Job1Link
		{
			get { return CustomerPortalCMS.GeneratedModels.CareersJobsCol6Controls.GetJob1Link(this); }
		}

		///<summary>
		/// Job 1 Title: Enter a title for this job
		///</summary>
		[ImplementPropertyType("job1Title")]
		public string Job1Title
		{
			get { return CustomerPortalCMS.GeneratedModels.CareersJobsCol6Controls.GetJob1Title(this); }
		}

		///<summary>
		/// Job 2 Description: Enter a description for this position
		///</summary>
		[ImplementPropertyType("job2Description")]
		public IHtmlString Job2Description
		{
			get { return CustomerPortalCMS.GeneratedModels.CareersJobsCol6Controls.GetJob2Description(this); }
		}

		///<summary>
		/// Job 2 Image: Choose an image for this Job
		///</summary>
		[ImplementPropertyType("job2Image")]
		public IPublishedContent Job2Image
		{
			get { return CustomerPortalCMS.GeneratedModels.CareersJobsCol6Controls.GetJob2Image(this); }
		}

		///<summary>
		/// Job 2 Image Caption: Enter a caption for this image (optional)
		///</summary>
		[ImplementPropertyType("job2ImageCaption")]
		public string Job2ImageCaption
		{
			get { return CustomerPortalCMS.GeneratedModels.CareersJobsCol6Controls.GetJob2ImageCaption(this); }
		}

		///<summary>
		/// Job 2 Image Video Link
		///</summary>
		[ImplementPropertyType("job2ImageVideoLink")]
		public Umbraco.Web.Models.RelatedLinks Job2ImageVideoLink
		{
			get { return CustomerPortalCMS.GeneratedModels.CareersJobsCol6Controls.GetJob2ImageVideoLink(this); }
		}

		///<summary>
		/// Job 2 Link: Choose a URL to link to (*the link caption text will be used for the text in the button)
		///</summary>
		[ImplementPropertyType("job2Link")]
		public Umbraco.Web.Models.RelatedLinks Job2Link
		{
			get { return CustomerPortalCMS.GeneratedModels.CareersJobsCol6Controls.GetJob2Link(this); }
		}

		///<summary>
		/// Job 2 Title: Enter a title for this job
		///</summary>
		[ImplementPropertyType("job2Title")]
		public string Job2Title
		{
			get { return CustomerPortalCMS.GeneratedModels.CareersJobsCol6Controls.GetJob2Title(this); }
		}

		///<summary>
		/// Job 3 Description: Enter a description for this position
		///</summary>
		[ImplementPropertyType("job3Description")]
		public IHtmlString Job3Description
		{
			get { return CustomerPortalCMS.GeneratedModels.CareersJobsCol6Controls.GetJob3Description(this); }
		}

		///<summary>
		/// Job 3 Image: Choose an image for this Job
		///</summary>
		[ImplementPropertyType("job3Image")]
		public IPublishedContent Job3Image
		{
			get { return CustomerPortalCMS.GeneratedModels.CareersJobsCol6Controls.GetJob3Image(this); }
		}

		///<summary>
		/// Job 3 Image Caption: Enter a caption for this image (optional)
		///</summary>
		[ImplementPropertyType("job3ImageCaption")]
		public string Job3ImageCaption
		{
			get { return CustomerPortalCMS.GeneratedModels.CareersJobsCol6Controls.GetJob3ImageCaption(this); }
		}

		///<summary>
		/// Job 3 Image Video Link
		///</summary>
		[ImplementPropertyType("job3ImageVideoLink")]
		public Umbraco.Web.Models.RelatedLinks Job3ImageVideoLink
		{
			get { return CustomerPortalCMS.GeneratedModels.CareersJobsCol6Controls.GetJob3ImageVideoLink(this); }
		}

		///<summary>
		/// Job 3 Link: Choose a URL to link to (*the link caption text will be used for the text in the button)
		///</summary>
		[ImplementPropertyType("job3Link")]
		public Umbraco.Web.Models.RelatedLinks Job3Link
		{
			get { return CustomerPortalCMS.GeneratedModels.CareersJobsCol6Controls.GetJob3Link(this); }
		}

		///<summary>
		/// Job 3 Title: Enter a title for this job
		///</summary>
		[ImplementPropertyType("job3Title")]
		public string Job3Title
		{
			get { return CustomerPortalCMS.GeneratedModels.CareersJobsCol6Controls.GetJob3Title(this); }
		}

		///<summary>
		/// Job 4 Description: Enter a description for this position
		///</summary>
		[ImplementPropertyType("job4Description")]
		public IHtmlString Job4Description
		{
			get { return CustomerPortalCMS.GeneratedModels.CareersJobsCol6Controls.GetJob4Description(this); }
		}

		///<summary>
		/// Job 4 Image: Choose an image for this Job
		///</summary>
		[ImplementPropertyType("job4Image")]
		public IPublishedContent Job4Image
		{
			get { return CustomerPortalCMS.GeneratedModels.CareersJobsCol6Controls.GetJob4Image(this); }
		}

		///<summary>
		/// Job 4 Image Caption: Enter a caption for this image (optional)
		///</summary>
		[ImplementPropertyType("job4ImageCaption")]
		public string Job4ImageCaption
		{
			get { return CustomerPortalCMS.GeneratedModels.CareersJobsCol6Controls.GetJob4ImageCaption(this); }
		}

		///<summary>
		/// Job 4 Image Video Link
		///</summary>
		[ImplementPropertyType("job4ImageVideoLink")]
		public Umbraco.Web.Models.RelatedLinks Job4ImageVideoLink
		{
			get { return CustomerPortalCMS.GeneratedModels.CareersJobsCol6Controls.GetJob4ImageVideoLink(this); }
		}

		///<summary>
		/// Job 4 Link: Choose a URL to link to (*the link caption text will be used for the text in the button)
		///</summary>
		[ImplementPropertyType("job4Link")]
		public Umbraco.Web.Models.RelatedLinks Job4Link
		{
			get { return CustomerPortalCMS.GeneratedModels.CareersJobsCol6Controls.GetJob4Link(this); }
		}

		///<summary>
		/// Job 4 Title: Enter a title for this job
		///</summary>
		[ImplementPropertyType("job4Title")]
		public string Job4Title
		{
			get { return CustomerPortalCMS.GeneratedModels.CareersJobsCol6Controls.GetJob4Title(this); }
		}

		///<summary>
		/// Job 5 Description: Enter a description for this position
		///</summary>
		[ImplementPropertyType("job5Description")]
		public IHtmlString Job5Description
		{
			get { return CustomerPortalCMS.GeneratedModels.CareersJobsCol6Controls.GetJob5Description(this); }
		}

		///<summary>
		/// Job 5 Image: Choose an image for this Job
		///</summary>
		[ImplementPropertyType("job5Image")]
		public IPublishedContent Job5Image
		{
			get { return CustomerPortalCMS.GeneratedModels.CareersJobsCol6Controls.GetJob5Image(this); }
		}

		///<summary>
		/// Job 5 Image Caption: Enter a caption for this image (optional)
		///</summary>
		[ImplementPropertyType("job5ImageCaption")]
		public string Job5ImageCaption
		{
			get { return CustomerPortalCMS.GeneratedModels.CareersJobsCol6Controls.GetJob5ImageCaption(this); }
		}

		///<summary>
		/// Job 5 Image Video Link
		///</summary>
		[ImplementPropertyType("job5ImageVideoLink")]
		public Umbraco.Web.Models.RelatedLinks Job5ImageVideoLink
		{
			get { return CustomerPortalCMS.GeneratedModels.CareersJobsCol6Controls.GetJob5ImageVideoLink(this); }
		}

		///<summary>
		/// Job 5 Link: Choose a URL to link to (*the link caption text will be used for the text in the button)
		///</summary>
		[ImplementPropertyType("job5Link")]
		public Umbraco.Web.Models.RelatedLinks Job5Link
		{
			get { return CustomerPortalCMS.GeneratedModels.CareersJobsCol6Controls.GetJob5Link(this); }
		}

		///<summary>
		/// Job 5 Title: Enter a title for this job
		///</summary>
		[ImplementPropertyType("job5Title")]
		public string Job5Title
		{
			get { return CustomerPortalCMS.GeneratedModels.CareersJobsCol6Controls.GetJob5Title(this); }
		}

		///<summary>
		/// Job 6 Description: Enter a description for this position
		///</summary>
		[ImplementPropertyType("job6Description")]
		public IHtmlString Job6Description
		{
			get { return CustomerPortalCMS.GeneratedModels.CareersJobsCol6Controls.GetJob6Description(this); }
		}

		///<summary>
		/// Job 6 Image: Choose an image for this Job
		///</summary>
		[ImplementPropertyType("job6Image")]
		public IPublishedContent Job6Image
		{
			get { return CustomerPortalCMS.GeneratedModels.CareersJobsCol6Controls.GetJob6Image(this); }
		}

		///<summary>
		/// Job 6 Image Caption: Enter a caption for this image (optional)
		///</summary>
		[ImplementPropertyType("job6ImageCaption")]
		public string Job6ImageCaption
		{
			get { return CustomerPortalCMS.GeneratedModels.CareersJobsCol6Controls.GetJob6ImageCaption(this); }
		}

		///<summary>
		/// Job 6 Image Video Link
		///</summary>
		[ImplementPropertyType("job6ImageVideoLink")]
		public Umbraco.Web.Models.RelatedLinks Job6ImageVideoLink
		{
			get { return CustomerPortalCMS.GeneratedModels.CareersJobsCol6Controls.GetJob6ImageVideoLink(this); }
		}

		///<summary>
		/// Job 6 Link: Choose a URL to link to (*the link caption text will be used for the text in the button)
		///</summary>
		[ImplementPropertyType("job6Link")]
		public Umbraco.Web.Models.RelatedLinks Job6Link
		{
			get { return CustomerPortalCMS.GeneratedModels.CareersJobsCol6Controls.GetJob6Link(this); }
		}

		///<summary>
		/// Job 6 Title: Enter a title for this job
		///</summary>
		[ImplementPropertyType("job6Title")]
		public string Job6Title
		{
			get { return CustomerPortalCMS.GeneratedModels.CareersJobsCol6Controls.GetJob6Title(this); }
		}

		///<summary>
		/// Job Heading: Enter the heading for this section
		///</summary>
		[ImplementPropertyType("jobHeading")]
		public string JobHeading
		{
			get { return CustomerPortalCMS.GeneratedModels.CareersJobsCol6Controls.GetJobHeading(this); }
		}

		///<summary>
		/// Brand Image 1: Choose a brand logo
		///</summary>
		[ImplementPropertyType("brandImage1")]
		public IPublishedContent BrandImage1
		{
			get { return CustomerPortalCMS.GeneratedModels.HorizontalBrandsControl.GetBrandImage1(this); }
		}

		///<summary>
		/// Brand Image 2: Choose a brand logo
		///</summary>
		[ImplementPropertyType("brandImage2")]
		public IPublishedContent BrandImage2
		{
			get { return CustomerPortalCMS.GeneratedModels.HorizontalBrandsControl.GetBrandImage2(this); }
		}

		///<summary>
		/// Brand Image 3: Choose a brand logo
		///</summary>
		[ImplementPropertyType("brandImage3")]
		public IPublishedContent BrandImage3
		{
			get { return CustomerPortalCMS.GeneratedModels.HorizontalBrandsControl.GetBrandImage3(this); }
		}

		///<summary>
		/// Brand Image 4: Choose a brand logo
		///</summary>
		[ImplementPropertyType("brandImage4")]
		public IPublishedContent BrandImage4
		{
			get { return CustomerPortalCMS.GeneratedModels.HorizontalBrandsControl.GetBrandImage4(this); }
		}

		///<summary>
		/// Brand Image 5: Choose a brand logo
		///</summary>
		[ImplementPropertyType("brandImage5")]
		public IPublishedContent BrandImage5
		{
			get { return CustomerPortalCMS.GeneratedModels.HorizontalBrandsControl.GetBrandImage5(this); }
		}

		///<summary>
		/// Brand Image 6: Choose a brand logo
		///</summary>
		[ImplementPropertyType("brandImage6")]
		public IPublishedContent BrandImage6
		{
			get { return CustomerPortalCMS.GeneratedModels.HorizontalBrandsControl.GetBrandImage6(this); }
		}

		///<summary>
		/// Brand Link 1: Choose a Link for this image (optional)
		///</summary>
		[ImplementPropertyType("brandLink1")]
		public Umbraco.Web.Models.RelatedLinks BrandLink1
		{
			get { return CustomerPortalCMS.GeneratedModels.HorizontalBrandsControl.GetBrandLink1(this); }
		}

		///<summary>
		/// Brand Link 2: Choose a Link for this image (optional)
		///</summary>
		[ImplementPropertyType("brandLink2")]
		public Umbraco.Web.Models.RelatedLinks BrandLink2
		{
			get { return CustomerPortalCMS.GeneratedModels.HorizontalBrandsControl.GetBrandLink2(this); }
		}

		///<summary>
		/// Brand Link 3: Choose a Link for this image (optional)
		///</summary>
		[ImplementPropertyType("brandLink3")]
		public Umbraco.Web.Models.RelatedLinks BrandLink3
		{
			get { return CustomerPortalCMS.GeneratedModels.HorizontalBrandsControl.GetBrandLink3(this); }
		}

		///<summary>
		/// Brand Link 4: Choose a Link for this image (optional)
		///</summary>
		[ImplementPropertyType("brandLink4")]
		public Umbraco.Web.Models.RelatedLinks BrandLink4
		{
			get { return CustomerPortalCMS.GeneratedModels.HorizontalBrandsControl.GetBrandLink4(this); }
		}

		///<summary>
		/// Brand Link 5: Choose a Link for this image (optional)
		///</summary>
		[ImplementPropertyType("brandLink5")]
		public Umbraco.Web.Models.RelatedLinks BrandLink5
		{
			get { return CustomerPortalCMS.GeneratedModels.HorizontalBrandsControl.GetBrandLink5(this); }
		}

		///<summary>
		/// Brand Link 6: Choose a Link for this image (optional)
		///</summary>
		[ImplementPropertyType("brandLink6")]
		public Umbraco.Web.Models.RelatedLinks BrandLink6
		{
			get { return CustomerPortalCMS.GeneratedModels.HorizontalBrandsControl.GetBrandLink6(this); }
		}

		///<summary>
		/// Meta Description: Best practice is to keep description under 150 characters
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription
		{
			get { return CustomerPortalCMS.GeneratedModels.SEocontrols.GetMetaDescription(this); }
		}

		///<summary>
		/// SEO Page Title: Overrides Title (from Page Title tab) and Name
		///</summary>
		[ImplementPropertyType("sEOPageTitle")]
		public string SEopageTitle
		{
			get { return CustomerPortalCMS.GeneratedModels.SEocontrols.GetSEopageTitle(this); }
		}

		///<summary>
		/// Hide If No Customer Selected?  (CP Sales Node Only!): (This is being replaced with Hide from navigation) Click this if you do not want this page to appear in the top nav
		///</summary>
		[ImplementPropertyType("excludeFromTopNavigation")]
		public bool ExcludeFromTopNavigation
		{
			get { return CustomerPortalCMS.GeneratedModels.TopNavigationControls.GetExcludeFromTopNavigation(this); }
		}

		///<summary>
		/// Hide from navigation: When checked, page will be hidden from navigation but still accessible by URL.
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return CustomerPortalCMS.GeneratedModels.TopNavigationControls.GetUmbracoNaviHide(this); }
		}
	}
}
