//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace CustomerPortalCMS.GeneratedModels
{
	// Mixin content Type 1295 with alias "careerSecondaryNavigationControls"
	/// <summary>Career Secondary Navigation Controls</summary>
	public partial interface ICareerSecondaryNavigationControls : IPublishedContent
	{
		/// <summary>Nav Link 1</summary>
		string NavLink1 { get; }

		/// <summary>Nav Link 2</summary>
		string NavLink2 { get; }

		/// <summary>Nav Link 3</summary>
		string NavLink3 { get; }

		/// <summary>Nav Link 4</summary>
		string NavLink4 { get; }

		/// <summary>Nav Link 5</summary>
		string NavLink5 { get; }

		/// <summary>Nav Link 6</summary>
		string NavLink6 { get; }

		/// <summary>Nav Link 7</summary>
		string NavLink7 { get; }

		/// <summary>Nav Link 8</summary>
		string NavLink8 { get; }
	}

	/// <summary>Career Secondary Navigation Controls</summary>
	[PublishedContentModel("careerSecondaryNavigationControls")]
	public partial class CareerSecondaryNavigationControls : PublishedContentModel, ICareerSecondaryNavigationControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "careerSecondaryNavigationControls";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public CareerSecondaryNavigationControls(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CareerSecondaryNavigationControls, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Nav Link 1: Enter the text to appear for the 1 Featured Career
		///</summary>
		[ImplementPropertyType("navLink1")]
		public string NavLink1
		{
			get { return GetNavLink1(this); }
		}

		/// <summary>Static getter for Nav Link 1</summary>
		public static string GetNavLink1(ICareerSecondaryNavigationControls that) { return that.GetPropertyValue<string>("navLink1"); }

		///<summary>
		/// Nav Link 2: Enter the text to appear for the 2 Featured Career
		///</summary>
		[ImplementPropertyType("navLink2")]
		public string NavLink2
		{
			get { return GetNavLink2(this); }
		}

		/// <summary>Static getter for Nav Link 2</summary>
		public static string GetNavLink2(ICareerSecondaryNavigationControls that) { return that.GetPropertyValue<string>("navLink2"); }

		///<summary>
		/// Nav Link 3: Enter the text to appear for Job 1
		///</summary>
		[ImplementPropertyType("navLink3")]
		public string NavLink3
		{
			get { return GetNavLink3(this); }
		}

		/// <summary>Static getter for Nav Link 3</summary>
		public static string GetNavLink3(ICareerSecondaryNavigationControls that) { return that.GetPropertyValue<string>("navLink3"); }

		///<summary>
		/// Nav Link 4: Enter the text to appear for Job 2
		///</summary>
		[ImplementPropertyType("navLink4")]
		public string NavLink4
		{
			get { return GetNavLink4(this); }
		}

		/// <summary>Static getter for Nav Link 4</summary>
		public static string GetNavLink4(ICareerSecondaryNavigationControls that) { return that.GetPropertyValue<string>("navLink4"); }

		///<summary>
		/// Nav Link 5: Enter the text to appear for Job 3
		///</summary>
		[ImplementPropertyType("navLink5")]
		public string NavLink5
		{
			get { return GetNavLink5(this); }
		}

		/// <summary>Static getter for Nav Link 5</summary>
		public static string GetNavLink5(ICareerSecondaryNavigationControls that) { return that.GetPropertyValue<string>("navLink5"); }

		///<summary>
		/// Nav Link 6: Enter the text to appear for Job 4
		///</summary>
		[ImplementPropertyType("navLink6")]
		public string NavLink6
		{
			get { return GetNavLink6(this); }
		}

		/// <summary>Static getter for Nav Link 6</summary>
		public static string GetNavLink6(ICareerSecondaryNavigationControls that) { return that.GetPropertyValue<string>("navLink6"); }

		///<summary>
		/// Nav Link 7: Enter the text to appear for Job 5
		///</summary>
		[ImplementPropertyType("navLink7")]
		public string NavLink7
		{
			get { return GetNavLink7(this); }
		}

		/// <summary>Static getter for Nav Link 7</summary>
		public static string GetNavLink7(ICareerSecondaryNavigationControls that) { return that.GetPropertyValue<string>("navLink7"); }

		///<summary>
		/// Nav Link 8: Enter the text to appear for Job 6
		///</summary>
		[ImplementPropertyType("navLink8")]
		public string NavLink8
		{
			get { return GetNavLink8(this); }
		}

		/// <summary>Static getter for Nav Link 8</summary>
		public static string GetNavLink8(ICareerSecondaryNavigationControls that) { return that.GetPropertyValue<string>("navLink8"); }
	}
}
