//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace CustomerPortalCMS.GeneratedModels
{
	// Mixin content Type 1293 with alias "careerContentControls"
	/// <summary>Career Content Controls</summary>
	public partial interface ICareerContentControls : IPublishedContent
	{
		/// <summary>Career Content</summary>
		IHtmlString CareerContent { get; }
	}

	/// <summary>Career Content Controls</summary>
	[PublishedContentModel("careerContentControls")]
	public partial class CareerContentControls : PublishedContentModel, ICareerContentControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "careerContentControls";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public CareerContentControls(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CareerContentControls, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Career Content
		///</summary>
		[ImplementPropertyType("careerContent")]
		public IHtmlString CareerContent
		{
			get { return GetCareerContent(this); }
		}

		/// <summary>Static getter for Career Content</summary>
		public static IHtmlString GetCareerContent(ICareerContentControls that) { return that.GetPropertyValue<IHtmlString>("careerContent"); }
	}
}
