//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace CustomerPortalCMS.GeneratedModels
{
	// Mixin content Type 1298 with alias "careerVisionControls"
	/// <summary>Career Vision Controls</summary>
	public partial interface ICareerVisionControls : IPublishedContent
	{
		/// <summary>Value 1 Desc</summary>
		IHtmlString Value1Desc { get; }

		/// <summary>Value 1 Image</summary>
		IPublishedContent Value1Image { get; }

		/// <summary>Value 2 Desc</summary>
		IHtmlString Value2Desc { get; }

		/// <summary>Value 2 Image</summary>
		IPublishedContent Value2Image { get; }

		/// <summary>Value 3 Desc</summary>
		IHtmlString Value3Desc { get; }

		/// <summary>Value 3 Image</summary>
		IPublishedContent Value3Image { get; }

		/// <summary>Value 4 Desc</summary>
		IHtmlString Value4Desc { get; }

		/// <summary>Value 4 Image</summary>
		IPublishedContent Value4Image { get; }

		/// <summary>Value 5 Desc</summary>
		IHtmlString Value5Desc { get; }

		/// <summary>Value 5 Image</summary>
		IPublishedContent Value5Image { get; }

		/// <summary>Value 6 Desc</summary>
		IHtmlString Value6Desc { get; }

		/// <summary>Value 6 Image</summary>
		IPublishedContent Value6Image { get; }

		/// <summary>Vision Description</summary>
		IHtmlString VisionDescription { get; }
	}

	/// <summary>Career Vision Controls</summary>
	[PublishedContentModel("careerVisionControls")]
	public partial class CareerVisionControls : PublishedContentModel, ICareerVisionControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "careerVisionControls";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public CareerVisionControls(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CareerVisionControls, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Value 1 Desc: Enter a description for value 1
		///</summary>
		[ImplementPropertyType("value1Desc")]
		public IHtmlString Value1Desc
		{
			get { return GetValue1Desc(this); }
		}

		/// <summary>Static getter for Value 1 Desc</summary>
		public static IHtmlString GetValue1Desc(ICareerVisionControls that) { return that.GetPropertyValue<IHtmlString>("value1Desc"); }

		///<summary>
		/// Value 1 Image: Choose an image for Value 1
		///</summary>
		[ImplementPropertyType("value1Image")]
		public IPublishedContent Value1Image
		{
			get { return GetValue1Image(this); }
		}

		/// <summary>Static getter for Value 1 Image</summary>
		public static IPublishedContent GetValue1Image(ICareerVisionControls that) { return that.GetPropertyValue<IPublishedContent>("value1Image"); }

		///<summary>
		/// Value 2 Desc: Enter a description for value 2
		///</summary>
		[ImplementPropertyType("value2Desc")]
		public IHtmlString Value2Desc
		{
			get { return GetValue2Desc(this); }
		}

		/// <summary>Static getter for Value 2 Desc</summary>
		public static IHtmlString GetValue2Desc(ICareerVisionControls that) { return that.GetPropertyValue<IHtmlString>("value2Desc"); }

		///<summary>
		/// Value 2 Image: Choose an image for Value 2
		///</summary>
		[ImplementPropertyType("value2Image")]
		public IPublishedContent Value2Image
		{
			get { return GetValue2Image(this); }
		}

		/// <summary>Static getter for Value 2 Image</summary>
		public static IPublishedContent GetValue2Image(ICareerVisionControls that) { return that.GetPropertyValue<IPublishedContent>("value2Image"); }

		///<summary>
		/// Value 3 Desc: Enter a description for value 3
		///</summary>
		[ImplementPropertyType("value3Desc")]
		public IHtmlString Value3Desc
		{
			get { return GetValue3Desc(this); }
		}

		/// <summary>Static getter for Value 3 Desc</summary>
		public static IHtmlString GetValue3Desc(ICareerVisionControls that) { return that.GetPropertyValue<IHtmlString>("value3Desc"); }

		///<summary>
		/// Value 3 Image: Choose an image for Value 3
		///</summary>
		[ImplementPropertyType("value3Image")]
		public IPublishedContent Value3Image
		{
			get { return GetValue3Image(this); }
		}

		/// <summary>Static getter for Value 3 Image</summary>
		public static IPublishedContent GetValue3Image(ICareerVisionControls that) { return that.GetPropertyValue<IPublishedContent>("value3Image"); }

		///<summary>
		/// Value 4 Desc: Enter a description for value 4
		///</summary>
		[ImplementPropertyType("value4Desc")]
		public IHtmlString Value4Desc
		{
			get { return GetValue4Desc(this); }
		}

		/// <summary>Static getter for Value 4 Desc</summary>
		public static IHtmlString GetValue4Desc(ICareerVisionControls that) { return that.GetPropertyValue<IHtmlString>("value4Desc"); }

		///<summary>
		/// Value 4 Image: Choose an image for Value 4
		///</summary>
		[ImplementPropertyType("value4Image")]
		public IPublishedContent Value4Image
		{
			get { return GetValue4Image(this); }
		}

		/// <summary>Static getter for Value 4 Image</summary>
		public static IPublishedContent GetValue4Image(ICareerVisionControls that) { return that.GetPropertyValue<IPublishedContent>("value4Image"); }

		///<summary>
		/// Value 5 Desc: Enter a description for value 5
		///</summary>
		[ImplementPropertyType("value5Desc")]
		public IHtmlString Value5Desc
		{
			get { return GetValue5Desc(this); }
		}

		/// <summary>Static getter for Value 5 Desc</summary>
		public static IHtmlString GetValue5Desc(ICareerVisionControls that) { return that.GetPropertyValue<IHtmlString>("value5Desc"); }

		///<summary>
		/// Value 5 Image: Choose an image for Value 5
		///</summary>
		[ImplementPropertyType("value5Image")]
		public IPublishedContent Value5Image
		{
			get { return GetValue5Image(this); }
		}

		/// <summary>Static getter for Value 5 Image</summary>
		public static IPublishedContent GetValue5Image(ICareerVisionControls that) { return that.GetPropertyValue<IPublishedContent>("value5Image"); }

		///<summary>
		/// Value 6 Desc: Enter a description for value 6
		///</summary>
		[ImplementPropertyType("value6Desc")]
		public IHtmlString Value6Desc
		{
			get { return GetValue6Desc(this); }
		}

		/// <summary>Static getter for Value 6 Desc</summary>
		public static IHtmlString GetValue6Desc(ICareerVisionControls that) { return that.GetPropertyValue<IHtmlString>("value6Desc"); }

		///<summary>
		/// Value 6 Image: Choose an image for Value 6
		///</summary>
		[ImplementPropertyType("value6Image")]
		public IPublishedContent Value6Image
		{
			get { return GetValue6Image(this); }
		}

		/// <summary>Static getter for Value 6 Image</summary>
		public static IPublishedContent GetValue6Image(ICareerVisionControls that) { return that.GetPropertyValue<IPublishedContent>("value6Image"); }

		///<summary>
		/// Vision Description: Enter a description of Builders vision
		///</summary>
		[ImplementPropertyType("visionDescription")]
		public IHtmlString VisionDescription
		{
			get { return GetVisionDescription(this); }
		}

		/// <summary>Static getter for Vision Description</summary>
		public static IHtmlString GetVisionDescription(ICareerVisionControls that) { return that.GetPropertyValue<IHtmlString>("visionDescription"); }
	}
}
