//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace CustomerPortalCMS.GeneratedModels
{
	// Mixin content Type 13107 with alias "careerWhyBuildersIntroControls1"
	/// <summary>Career Why Builders Intro Controls-WithCrop</summary>
	public partial interface ICareerWhyBuildersIntroControls1 : IPublishedContent
	{
		/// <summary>Left Column Image</summary>
		Umbraco.Web.Models.ImageCropDataSet LeftColumnImage { get; }

		/// <summary>Left Column Quote</summary>
		IHtmlString LeftColumnQuote { get; }

		/// <summary>Left Column Quote By</summary>
		string LeftColumnQuoteBy { get; }

		/// <summary>Right Column Bottom Text</summary>
		IHtmlString RightColumnBottomText { get; }

		/// <summary>Right Column Quote</summary>
		IHtmlString RightColumnQuote { get; }

		/// <summary>Right Column Quote By</summary>
		string RightColumnQuoteBy { get; }

		/// <summary>Right Column Top Text</summary>
		IHtmlString RightColumnTopText { get; }
	}

	/// <summary>Career Why Builders Intro Controls-WithCrop</summary>
	[PublishedContentModel("careerWhyBuildersIntroControls1")]
	public partial class CareerWhyBuildersIntroControls1 : PublishedContentModel, ICareerWhyBuildersIntroControls1
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "careerWhyBuildersIntroControls1";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public CareerWhyBuildersIntroControls1(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CareerWhyBuildersIntroControls1, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Left Column Image: Choose a image for the left column
		///</summary>
		[ImplementPropertyType("leftColumnImage")]
		public Umbraco.Web.Models.ImageCropDataSet LeftColumnImage
		{
			get { return GetLeftColumnImage(this); }
		}

		/// <summary>Static getter for Left Column Image</summary>
		public static Umbraco.Web.Models.ImageCropDataSet GetLeftColumnImage(ICareerWhyBuildersIntroControls1 that) { return that.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("leftColumnImage"); }

		///<summary>
		/// Left Column Quote: Enter the quote for the left column
		///</summary>
		[ImplementPropertyType("leftColumnQuote")]
		public IHtmlString LeftColumnQuote
		{
			get { return GetLeftColumnQuote(this); }
		}

		/// <summary>Static getter for Left Column Quote</summary>
		public static IHtmlString GetLeftColumnQuote(ICareerWhyBuildersIntroControls1 that) { return that.GetPropertyValue<IHtmlString>("leftColumnQuote"); }

		///<summary>
		/// Left Column Quote By: Left column quote by (optional)
		///</summary>
		[ImplementPropertyType("leftColumnQuoteBy")]
		public string LeftColumnQuoteBy
		{
			get { return GetLeftColumnQuoteBy(this); }
		}

		/// <summary>Static getter for Left Column Quote By</summary>
		public static string GetLeftColumnQuoteBy(ICareerWhyBuildersIntroControls1 that) { return that.GetPropertyValue<string>("leftColumnQuoteBy"); }

		///<summary>
		/// Right Column Bottom Text: Enter the text to appear on the right side after the quote
		///</summary>
		[ImplementPropertyType("rightColumnBottomText")]
		public IHtmlString RightColumnBottomText
		{
			get { return GetRightColumnBottomText(this); }
		}

		/// <summary>Static getter for Right Column Bottom Text</summary>
		public static IHtmlString GetRightColumnBottomText(ICareerWhyBuildersIntroControls1 that) { return that.GetPropertyValue<IHtmlString>("rightColumnBottomText"); }

		///<summary>
		/// Right Column Quote: Enter the quote for the right column
		///</summary>
		[ImplementPropertyType("rightColumnQuote")]
		public IHtmlString RightColumnQuote
		{
			get { return GetRightColumnQuote(this); }
		}

		/// <summary>Static getter for Right Column Quote</summary>
		public static IHtmlString GetRightColumnQuote(ICareerWhyBuildersIntroControls1 that) { return that.GetPropertyValue<IHtmlString>("rightColumnQuote"); }

		///<summary>
		/// Right Column Quote By: Right column quote by (optional)
		///</summary>
		[ImplementPropertyType("rightColumnQuoteBy")]
		public string RightColumnQuoteBy
		{
			get { return GetRightColumnQuoteBy(this); }
		}

		/// <summary>Static getter for Right Column Quote By</summary>
		public static string GetRightColumnQuoteBy(ICareerWhyBuildersIntroControls1 that) { return that.GetPropertyValue<string>("rightColumnQuoteBy"); }

		///<summary>
		/// Right Column Top Text: Enter the text to appear on the right side before the quote
		///</summary>
		[ImplementPropertyType("rightColumnTopText")]
		public IHtmlString RightColumnTopText
		{
			get { return GetRightColumnTopText(this); }
		}

		/// <summary>Static getter for Right Column Top Text</summary>
		public static IHtmlString GetRightColumnTopText(ICareerWhyBuildersIntroControls1 that) { return that.GetPropertyValue<IHtmlString>("rightColumnTopText"); }
	}
}
