//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace CustomerPortalCMS.GeneratedModels
{
	/// <summary>Construction Type</summary>
	[PublishedContentModel("ConstructionType")]
	public partial class ConstructionType : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "ConstructionType";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ConstructionType(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ConstructionType, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// About
		///</summary>
		[ImplementPropertyType("about")]
		public IHtmlString About
		{
			get { return this.GetPropertyValue<IHtmlString>("about"); }
		}

		///<summary>
		/// HomePage Background Image: Resolution:- 500x532
		///</summary>
		[ImplementPropertyType("homePageBackgroundImage")]
		public Umbraco.Web.Models.ImageCropDataSet HomePageBackgroundImage
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("homePageBackgroundImage"); }
		}

		///<summary>
		/// HomePage Button
		///</summary>
		[ImplementPropertyType("homePageButton")]
		public Umbraco.Web.Models.RelatedLinks HomePageButton
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("homePageButton"); }
		}

		///<summary>
		/// Image 1
		///</summary>
		[ImplementPropertyType("image1")]
		public Umbraco.Web.Models.ImageCropDataSet Image1
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("image1"); }
		}

		///<summary>
		/// Image 2
		///</summary>
		[ImplementPropertyType("image2")]
		public Umbraco.Web.Models.ImageCropDataSet Image2
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("image2"); }
		}

		///<summary>
		/// Show On HomePage
		///</summary>
		[ImplementPropertyType("showOnHomePage")]
		public bool ShowOnHomePage
		{
			get { return this.GetPropertyValue<bool>("showOnHomePage"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return this.GetPropertyValue<string>("title"); }
		}
	}
}
