//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace CustomerPortalCMS.GeneratedModels
{
	/// <summary>Contact Us</summary>
	[PublishedContentModel("contactUs")]
	public partial class ContactUs : PublishedContentModel, IBasicContentControls, IPageTitle, ISEocontrols, ITopNavigationControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "contactUs";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ContactUs(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContactUs, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Careers Alias: Subject Line Item (RE: Careers)
		///</summary>
		[ImplementPropertyType("careersAlias")]
		public string CareersAlias
		{
			get { return this.GetPropertyValue<string>("careersAlias"); }
		}

		///<summary>
		/// Careers Contact: The email address(s) separated by a comma, to send contact us emails marked as careers.
		///</summary>
		[ImplementPropertyType("careersContact")]
		public string CareersContact
		{
			get { return this.GetPropertyValue<string>("careersContact"); }
		}

		///<summary>
		/// ContactIntroduction: Introductory Paragraph
		///</summary>
		[ImplementPropertyType("contactIntroduction")]
		public IHtmlString ContactIntroduction
		{
			get { return this.GetPropertyValue<IHtmlString>("contactIntroduction"); }
		}

		///<summary>
		/// Other Alias: Subject Line Item (RE: Other)
		///</summary>
		[ImplementPropertyType("otherAlias")]
		public string OtherAlias
		{
			get { return this.GetPropertyValue<string>("otherAlias"); }
		}

		///<summary>
		/// Other Contact: The email address(s) separated by a comma, to send contact us emails marked as other.
		///</summary>
		[ImplementPropertyType("otherContact")]
		public string OtherContact
		{
			get { return this.GetPropertyValue<string>("otherContact"); }
		}

		///<summary>
		/// Safety Alias: Subject Line Item (RE: Safety)
		///</summary>
		[ImplementPropertyType("safetyAlias")]
		public string SafetyAlias
		{
			get { return this.GetPropertyValue<string>("safetyAlias"); }
		}

		///<summary>
		/// Safety Contact: The email address(s) separated by a comma, to send safety related contact us emails
		///</summary>
		[ImplementPropertyType("safetyContact")]
		public string SafetyContact
		{
			get { return this.GetPropertyValue<string>("safetyContact"); }
		}

		///<summary>
		/// Sales Alias: Subject Line Item (RE: Sales)
		///</summary>
		[ImplementPropertyType("salesAlias")]
		public string SalesAlias
		{
			get { return this.GetPropertyValue<string>("salesAlias"); }
		}

		///<summary>
		/// Sales Contact: The email address(s) separated by a comma, to send sales related contact us emails.
		///</summary>
		[ImplementPropertyType("salesContact")]
		public string SalesContact
		{
			get { return this.GetPropertyValue<string>("salesContact"); }
		}

		///<summary>
		/// Warranty Alias: Subject Line Item (RE: Warranty )
		///</summary>
		[ImplementPropertyType("warrantyAlias")]
		public string WarrantyAlias
		{
			get { return this.GetPropertyValue<string>("warrantyAlias"); }
		}

		///<summary>
		/// Warranty Contact: The email address(s) separated by a comma, to send warranty related contact us emails.
		///</summary>
		[ImplementPropertyType("warrantyContact")]
		public string WarrantyContact
		{
			get { return this.GetPropertyValue<string>("warrantyContact"); }
		}

		///<summary>
		/// Content: Replacing the Content Grid
		///</summary>
		[ImplementPropertyType("pageContent")]
		public IHtmlString PageContent
		{
			get { return CustomerPortalCMS.GeneratedModels.BasicContentControls.GetPageContent(this); }
		}

		///<summary>
		/// Header Image: Choose the banner image for this page
		///</summary>
		[ImplementPropertyType("headerImage")]
		public IPublishedContent HeaderImage
		{
			get { return CustomerPortalCMS.GeneratedModels.PageTitle.GetHeaderImage(this); }
		}

		///<summary>
		/// Title: Enter the Page Title - overrides page Name
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return CustomerPortalCMS.GeneratedModels.PageTitle.GetTitle(this); }
		}

		///<summary>
		/// Meta Description: Best practice is to keep description under 150 characters
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription
		{
			get { return CustomerPortalCMS.GeneratedModels.SEocontrols.GetMetaDescription(this); }
		}

		///<summary>
		/// SEO Page Title: Overrides Title (from Page Title tab) and Name
		///</summary>
		[ImplementPropertyType("sEOPageTitle")]
		public string SEopageTitle
		{
			get { return CustomerPortalCMS.GeneratedModels.SEocontrols.GetSEopageTitle(this); }
		}

		///<summary>
		/// Hide If No Customer Selected?  (CP Sales Node Only!): (This is being replaced with Hide from navigation) Click this if you do not want this page to appear in the top nav
		///</summary>
		[ImplementPropertyType("excludeFromTopNavigation")]
		public bool ExcludeFromTopNavigation
		{
			get { return CustomerPortalCMS.GeneratedModels.TopNavigationControls.GetExcludeFromTopNavigation(this); }
		}

		///<summary>
		/// Hide from navigation: When checked, page will be hidden from navigation but still accessible by URL.
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return CustomerPortalCMS.GeneratedModels.TopNavigationControls.GetUmbracoNaviHide(this); }
		}
	}
}
