//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace CustomerPortalCMS.GeneratedModels
{
	/// <summary>Global Configuration</summary>
	[PublishedContentModel("customerPortalGlobalConfig")]
	public partial class CustomerPortalGlobalConfig : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "customerPortalGlobalConfig";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public CustomerPortalGlobalConfig(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CustomerPortalGlobalConfig, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Current Status: Customer Portal Status
		///</summary>
		[ImplementPropertyType("customerPortalCurrentStatus")]
		public string CustomerPortalCurrentStatus
		{
			get { return this.GetPropertyValue<string>("customerPortalCurrentStatus"); }
		}

		///<summary>
		/// Outage Message: Message to display to user when customer portal is offline.
		///</summary>
		[ImplementPropertyType("customerPortalOutageMessage")]
		public IHtmlString CustomerPortalOutageMessage
		{
			get { return this.GetPropertyValue<IHtmlString>("customerPortalOutageMessage"); }
		}

		///<summary>
		/// Registration Disabled: Disable Registration (Invite Only)?
		///</summary>
		[ImplementPropertyType("customerPortalRegistrationDisabled")]
		public bool CustomerPortalRegistrationDisabled
		{
			get { return this.GetPropertyValue<bool>("customerPortalRegistrationDisabled"); }
		}
	}
}
