//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace CustomerPortalCMS.GeneratedModels
{
	// Mixin content Type 1239 with alias "customerControls"
	/// <summary>Customer Controls</summary>
	public partial interface ICustomerControls : IPublishedContent
	{
		/// <summary>customerMaintenenceEmail</summary>
		string CustomerMaintenenceEmail { get; }

		/// <summary>editAuthorizedSignersEmailSubject</summary>
		string EditAuthorizedSignersEmailSubject { get; }

		/// <summary>editContactDetailsEmailSubject</summary>
		string EditContactDetailsEmailSubject { get; }
	}

	/// <summary>Customer Controls</summary>
	[PublishedContentModel("customerControls")]
	public partial class CustomerControls : PublishedContentModel, ICustomerControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "customerControls";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public CustomerControls(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CustomerControls, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// customerMaintenenceEmail
		///</summary>
		[ImplementPropertyType("customerMaintenenceEmail")]
		public string CustomerMaintenenceEmail
		{
			get { return GetCustomerMaintenenceEmail(this); }
		}

		/// <summary>Static getter for customerMaintenenceEmail</summary>
		public static string GetCustomerMaintenenceEmail(ICustomerControls that) { return that.GetPropertyValue<string>("customerMaintenenceEmail"); }

		///<summary>
		/// editAuthorizedSignersEmailSubject
		///</summary>
		[ImplementPropertyType("editAuthorizedSignersEmailSubject")]
		public string EditAuthorizedSignersEmailSubject
		{
			get { return GetEditAuthorizedSignersEmailSubject(this); }
		}

		/// <summary>Static getter for editAuthorizedSignersEmailSubject</summary>
		public static string GetEditAuthorizedSignersEmailSubject(ICustomerControls that) { return that.GetPropertyValue<string>("editAuthorizedSignersEmailSubject"); }

		///<summary>
		/// editContactDetailsEmailSubject
		///</summary>
		[ImplementPropertyType("editContactDetailsEmailSubject")]
		public string EditContactDetailsEmailSubject
		{
			get { return GetEditContactDetailsEmailSubject(this); }
		}

		/// <summary>Static getter for editContactDetailsEmailSubject</summary>
		public static string GetEditContactDetailsEmailSubject(ICustomerControls that) { return that.GetPropertyValue<string>("editContactDetailsEmailSubject"); }
	}
}
