//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace CustomerPortalCMS.GeneratedModels
{
	/// <summary>Document Page</summary>
	[PublishedContentModel("docList")]
	public partial class DocList : PublishedContentModel, IPageTitle, ISEocontrols, ITopNavigationControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "docList";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public DocList(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<DocList, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Header Image: Choose the banner image for this page
		///</summary>
		[ImplementPropertyType("headerImage")]
		public IPublishedContent HeaderImage
		{
			get { return CustomerPortalCMS.GeneratedModels.PageTitle.GetHeaderImage(this); }
		}

		///<summary>
		/// Title: Enter the Page Title - overrides page Name
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return CustomerPortalCMS.GeneratedModels.PageTitle.GetTitle(this); }
		}

		///<summary>
		/// Meta Description: Best practice is to keep description under 150 characters
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription
		{
			get { return CustomerPortalCMS.GeneratedModels.SEocontrols.GetMetaDescription(this); }
		}

		///<summary>
		/// SEO Page Title: Overrides Title (from Page Title tab) and Name
		///</summary>
		[ImplementPropertyType("sEOPageTitle")]
		public string SEopageTitle
		{
			get { return CustomerPortalCMS.GeneratedModels.SEocontrols.GetSEopageTitle(this); }
		}

		///<summary>
		/// Hide If No Customer Selected?  (CP Sales Node Only!): (This is being replaced with Hide from navigation) Click this if you do not want this page to appear in the top nav
		///</summary>
		[ImplementPropertyType("excludeFromTopNavigation")]
		public bool ExcludeFromTopNavigation
		{
			get { return CustomerPortalCMS.GeneratedModels.TopNavigationControls.GetExcludeFromTopNavigation(this); }
		}

		///<summary>
		/// Hide from navigation: When checked, page will be hidden from navigation but still accessible by URL.
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return CustomerPortalCMS.GeneratedModels.TopNavigationControls.GetUmbracoNaviHide(this); }
		}
	}
}
