//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace CustomerPortalCMS.GeneratedModels
{
	// Mixin content Type 1275 with alias "homeCarouselControls"
	/// <summary>Home Carousel Controls</summary>
	public partial interface IHomeCarouselControls : IPublishedContent
	{
		/// <summary>Carousel Image 1</summary>
		IPublishedContent CarouselImage1 { get; }

		/// <summary>Carousel Image 1 Caption</summary>
		string CarouselImage1Caption { get; }

		/// <summary>Carousel Image 2</summary>
		IPublishedContent CarouselImage2 { get; }

		/// <summary>Carousel Image 2 Caption</summary>
		string CarouselImage2Caption { get; }

		/// <summary>Carousel Image 3</summary>
		IPublishedContent CarouselImage3 { get; }

		/// <summary>Carousel Image 3 Caption</summary>
		string CarouselImage3Caption { get; }

		/// <summary>Carousel Image 4</summary>
		IPublishedContent CarouselImage4 { get; }

		/// <summary>Carousel Image 4 Caption</summary>
		string CarouselImage4Caption { get; }
	}

	/// <summary>Home Carousel Controls</summary>
	[PublishedContentModel("homeCarouselControls")]
	public partial class HomeCarouselControls : PublishedContentModel, IHomeCarouselControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "homeCarouselControls";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HomeCarouselControls(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HomeCarouselControls, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Carousel Image 1: Select the image to appear first in the carousel
		///</summary>
		[ImplementPropertyType("carouselImage1")]
		public IPublishedContent CarouselImage1
		{
			get { return GetCarouselImage1(this); }
		}

		/// <summary>Static getter for Carousel Image 1</summary>
		public static IPublishedContent GetCarouselImage1(IHomeCarouselControls that) { return that.GetPropertyValue<IPublishedContent>("carouselImage1"); }

		///<summary>
		/// Carousel Image 1 Caption: Enter the caption to appear on the first carousel image
		///</summary>
		[ImplementPropertyType("carouselImage1Caption")]
		public string CarouselImage1Caption
		{
			get { return GetCarouselImage1Caption(this); }
		}

		/// <summary>Static getter for Carousel Image 1 Caption</summary>
		public static string GetCarouselImage1Caption(IHomeCarouselControls that) { return that.GetPropertyValue<string>("carouselImage1Caption"); }

		///<summary>
		/// Carousel Image 2: Select the image to appear second in the carousel
		///</summary>
		[ImplementPropertyType("carouselImage2")]
		public IPublishedContent CarouselImage2
		{
			get { return GetCarouselImage2(this); }
		}

		/// <summary>Static getter for Carousel Image 2</summary>
		public static IPublishedContent GetCarouselImage2(IHomeCarouselControls that) { return that.GetPropertyValue<IPublishedContent>("carouselImage2"); }

		///<summary>
		/// Carousel Image 2 Caption: Enter the caption to appear on the second carousel image
		///</summary>
		[ImplementPropertyType("carouselImage2Caption")]
		public string CarouselImage2Caption
		{
			get { return GetCarouselImage2Caption(this); }
		}

		/// <summary>Static getter for Carousel Image 2 Caption</summary>
		public static string GetCarouselImage2Caption(IHomeCarouselControls that) { return that.GetPropertyValue<string>("carouselImage2Caption"); }

		///<summary>
		/// Carousel Image 3: Select the image to appear third in the carousel
		///</summary>
		[ImplementPropertyType("carouselImage3")]
		public IPublishedContent CarouselImage3
		{
			get { return GetCarouselImage3(this); }
		}

		/// <summary>Static getter for Carousel Image 3</summary>
		public static IPublishedContent GetCarouselImage3(IHomeCarouselControls that) { return that.GetPropertyValue<IPublishedContent>("carouselImage3"); }

		///<summary>
		/// Carousel Image 3 Caption: Enter the caption to appear on the third carousel image
		///</summary>
		[ImplementPropertyType("carouselImage3Caption")]
		public string CarouselImage3Caption
		{
			get { return GetCarouselImage3Caption(this); }
		}

		/// <summary>Static getter for Carousel Image 3 Caption</summary>
		public static string GetCarouselImage3Caption(IHomeCarouselControls that) { return that.GetPropertyValue<string>("carouselImage3Caption"); }

		///<summary>
		/// Carousel Image 4: Select the image to appear fourth in the carousel
		///</summary>
		[ImplementPropertyType("carouselImage4")]
		public IPublishedContent CarouselImage4
		{
			get { return GetCarouselImage4(this); }
		}

		/// <summary>Static getter for Carousel Image 4</summary>
		public static IPublishedContent GetCarouselImage4(IHomeCarouselControls that) { return that.GetPropertyValue<IPublishedContent>("carouselImage4"); }

		///<summary>
		/// Carousel Image 4 Caption: Enter the caption to appear on the fourth carousel image
		///</summary>
		[ImplementPropertyType("carouselImage4Caption")]
		public string CarouselImage4Caption
		{
			get { return GetCarouselImage4Caption(this); }
		}

		/// <summary>Static getter for Carousel Image 4 Caption</summary>
		public static string GetCarouselImage4Caption(IHomeCarouselControls that) { return that.GetPropertyValue<string>("carouselImage4Caption"); }
	}
}
