//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace CustomerPortalCMS.GeneratedModels
{
	/// <summary>Home</summary>
	[PublishedContentModel("home")]
	public partial class Home : PublishedContentModel, IHomeCarouselControls, IHomeConstructionControls, IHomeEmploymentControls, IHomeFeaturedControls, ISEocontrols
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "home";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Home(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Home, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Carousel Timer: Interval between image-change in milliseconds
		///</summary>
		[ImplementPropertyType("carouselTimer")]
		public decimal CarouselTimer
		{
			get { return this.GetPropertyValue<decimal>("carouselTimer"); }
		}

		///<summary>
		/// Carousel Image 1: Select the image to appear first in the carousel
		///</summary>
		[ImplementPropertyType("carouselImage1")]
		public IPublishedContent CarouselImage1
		{
			get { return CustomerPortalCMS.GeneratedModels.HomeCarouselControls.GetCarouselImage1(this); }
		}

		///<summary>
		/// Carousel Image 1 Caption: Enter the caption to appear on the first carousel image
		///</summary>
		[ImplementPropertyType("carouselImage1Caption")]
		public string CarouselImage1Caption
		{
			get { return CustomerPortalCMS.GeneratedModels.HomeCarouselControls.GetCarouselImage1Caption(this); }
		}

		///<summary>
		/// Carousel Image 2: Select the image to appear second in the carousel
		///</summary>
		[ImplementPropertyType("carouselImage2")]
		public IPublishedContent CarouselImage2
		{
			get { return CustomerPortalCMS.GeneratedModels.HomeCarouselControls.GetCarouselImage2(this); }
		}

		///<summary>
		/// Carousel Image 2 Caption: Enter the caption to appear on the second carousel image
		///</summary>
		[ImplementPropertyType("carouselImage2Caption")]
		public string CarouselImage2Caption
		{
			get { return CustomerPortalCMS.GeneratedModels.HomeCarouselControls.GetCarouselImage2Caption(this); }
		}

		///<summary>
		/// Carousel Image 3: Select the image to appear third in the carousel
		///</summary>
		[ImplementPropertyType("carouselImage3")]
		public IPublishedContent CarouselImage3
		{
			get { return CustomerPortalCMS.GeneratedModels.HomeCarouselControls.GetCarouselImage3(this); }
		}

		///<summary>
		/// Carousel Image 3 Caption: Enter the caption to appear on the third carousel image
		///</summary>
		[ImplementPropertyType("carouselImage3Caption")]
		public string CarouselImage3Caption
		{
			get { return CustomerPortalCMS.GeneratedModels.HomeCarouselControls.GetCarouselImage3Caption(this); }
		}

		///<summary>
		/// Carousel Image 4: Select the image to appear fourth in the carousel
		///</summary>
		[ImplementPropertyType("carouselImage4")]
		public IPublishedContent CarouselImage4
		{
			get { return CustomerPortalCMS.GeneratedModels.HomeCarouselControls.GetCarouselImage4(this); }
		}

		///<summary>
		/// Carousel Image 4 Caption: Enter the caption to appear on the fourth carousel image
		///</summary>
		[ImplementPropertyType("carouselImage4Caption")]
		public string CarouselImage4Caption
		{
			get { return CustomerPortalCMS.GeneratedModels.HomeCarouselControls.GetCarouselImage4Caption(this); }
		}

		///<summary>
		/// Construction Type Title
		///</summary>
		[ImplementPropertyType("constructionTypeTitle")]
		public string ConstructionTypeTitle
		{
			get { return CustomerPortalCMS.GeneratedModels.HomeConstructionControls.GetConstructionTypeTitle(this); }
		}

		///<summary>
		/// Type 1: Enter the text for the link
		///</summary>
		[ImplementPropertyType("type1")]
		public string Type1
		{
			get { return CustomerPortalCMS.GeneratedModels.HomeConstructionControls.GetType1(this); }
		}

		///<summary>
		/// Type 1 Link: Choose the page to link to
		///</summary>
		[ImplementPropertyType("type1Link")]
		public Umbraco.Web.Models.RelatedLinks Type1Link
		{
			get { return CustomerPortalCMS.GeneratedModels.HomeConstructionControls.GetType1Link(this); }
		}

		///<summary>
		/// Type 2: Enter the text for the link
		///</summary>
		[ImplementPropertyType("type2")]
		public string Type2
		{
			get { return CustomerPortalCMS.GeneratedModels.HomeConstructionControls.GetType2(this); }
		}

		///<summary>
		/// Type 2 Link: Choose the page to link to
		///</summary>
		[ImplementPropertyType("type2Link")]
		public Umbraco.Web.Models.RelatedLinks Type2Link
		{
			get { return CustomerPortalCMS.GeneratedModels.HomeConstructionControls.GetType2Link(this); }
		}

		///<summary>
		/// Type 3: Enter the text for the link
		///</summary>
		[ImplementPropertyType("type3")]
		public string Type3
		{
			get { return CustomerPortalCMS.GeneratedModels.HomeConstructionControls.GetType3(this); }
		}

		///<summary>
		/// Type 3 Link: Choose a page to link to
		///</summary>
		[ImplementPropertyType("type3Link")]
		public Umbraco.Web.Models.RelatedLinks Type3Link
		{
			get { return CustomerPortalCMS.GeneratedModels.HomeConstructionControls.GetType3Link(this); }
		}

		///<summary>
		/// Employment Msg: Enter the disclaimer for employment
		///</summary>
		[ImplementPropertyType("employmentMsg")]
		public string EmploymentMsg
		{
			get { return CustomerPortalCMS.GeneratedModels.HomeEmploymentControls.GetEmploymentMsg(this); }
		}

		///<summary>
		/// Feature 1 Button Link: Enter the link for the "Learn More" button if it should appear
		///</summary>
		[ImplementPropertyType("feature1ButtonLink")]
		public Umbraco.Web.Models.RelatedLinks Feature1ButtonLink
		{
			get { return CustomerPortalCMS.GeneratedModels.HomeFeaturedControls.GetFeature1ButtonLink(this); }
		}

		///<summary>
		/// Feature 1 Direct Video Link: Choose the video to play in the popup
		///</summary>
		[ImplementPropertyType("feature1DirectVideoLink")]
		public Umbraco.Web.Models.RelatedLinks Feature1DirectVideoLink
		{
			get { return CustomerPortalCMS.GeneratedModels.HomeFeaturedControls.GetFeature1DirectVideoLink(this); }
		}

		///<summary>
		/// Feature 1 Label: Enter the text for feature 1.
		///</summary>
		[ImplementPropertyType("feature1Label")]
		public string Feature1Label
		{
			get { return CustomerPortalCMS.GeneratedModels.HomeFeaturedControls.GetFeature1Label(this); }
		}

		///<summary>
		/// Feature 1 Thumbnail: Choose the thumbnail image for feature 1
		///</summary>
		[ImplementPropertyType("feature1Thumbnail")]
		public IPublishedContent Feature1Thumbnail
		{
			get { return CustomerPortalCMS.GeneratedModels.HomeFeaturedControls.GetFeature1Thumbnail(this); }
		}

		///<summary>
		/// Feature 1 Video Link: If this should link to a video, enter the link here.
		///</summary>
		[ImplementPropertyType("feature1VideoLink")]
		public Umbraco.Web.Models.RelatedLinks Feature1VideoLink
		{
			get { return CustomerPortalCMS.GeneratedModels.HomeFeaturedControls.GetFeature1VideoLink(this); }
		}

		///<summary>
		/// Feature 2 Button Link: Enter the link for the "Learn More" button if it should appear.
		///</summary>
		[ImplementPropertyType("feature2ButtonLink")]
		public Umbraco.Web.Models.RelatedLinks Feature2ButtonLink
		{
			get { return CustomerPortalCMS.GeneratedModels.HomeFeaturedControls.GetFeature2ButtonLink(this); }
		}

		///<summary>
		/// Feature 2 Direct Video Link: Choose the video to play in the popup
		///</summary>
		[ImplementPropertyType("feature2DirectVideoLink")]
		public Umbraco.Web.Models.RelatedLinks Feature2DirectVideoLink
		{
			get { return CustomerPortalCMS.GeneratedModels.HomeFeaturedControls.GetFeature2DirectVideoLink(this); }
		}

		///<summary>
		/// Feature 2 Label: Enter the text for feature 2
		///</summary>
		[ImplementPropertyType("feature2Label")]
		public string Feature2Label
		{
			get { return CustomerPortalCMS.GeneratedModels.HomeFeaturedControls.GetFeature2Label(this); }
		}

		///<summary>
		/// Feature 2 Thumbnail: Choose the thumbnail picture for feature 2.
		///</summary>
		[ImplementPropertyType("feature2Thumbnail")]
		public IPublishedContent Feature2Thumbnail
		{
			get { return CustomerPortalCMS.GeneratedModels.HomeFeaturedControls.GetFeature2Thumbnail(this); }
		}

		///<summary>
		/// Feature 2 Video Link: If this should link to a video, enter the link here.
		///</summary>
		[ImplementPropertyType("feature2VideoLink")]
		public Umbraco.Web.Models.RelatedLinks Feature2VideoLink
		{
			get { return CustomerPortalCMS.GeneratedModels.HomeFeaturedControls.GetFeature2VideoLink(this); }
		}

		///<summary>
		/// Feature 3 Button Link: Enter the link for the "Learn More" button if it should appear.
		///</summary>
		[ImplementPropertyType("feature3ButtonLink")]
		public Umbraco.Web.Models.RelatedLinks Feature3ButtonLink
		{
			get { return CustomerPortalCMS.GeneratedModels.HomeFeaturedControls.GetFeature3ButtonLink(this); }
		}

		///<summary>
		/// Feature 3 Direct Video Link: Choose the video to play in the popup
		///</summary>
		[ImplementPropertyType("feature3DirectVideoLink")]
		public Umbraco.Web.Models.RelatedLinks Feature3DirectVideoLink
		{
			get { return CustomerPortalCMS.GeneratedModels.HomeFeaturedControls.GetFeature3DirectVideoLink(this); }
		}

		///<summary>
		/// Feature 3 Label: Enter the text for feature 3
		///</summary>
		[ImplementPropertyType("feature3Label")]
		public string Feature3Label
		{
			get { return CustomerPortalCMS.GeneratedModels.HomeFeaturedControls.GetFeature3Label(this); }
		}

		///<summary>
		/// Feature 3 Thumbnail: Choose the thumbnail image for feature 3
		///</summary>
		[ImplementPropertyType("feature3Thumbnail")]
		public IPublishedContent Feature3Thumbnail
		{
			get { return CustomerPortalCMS.GeneratedModels.HomeFeaturedControls.GetFeature3Thumbnail(this); }
		}

		///<summary>
		/// Feature 3 Video Link: If this should link to a list of videos enter the link here.
		///</summary>
		[ImplementPropertyType("feature3VideoLink")]
		public Umbraco.Web.Models.RelatedLinks Feature3VideoLink
		{
			get { return CustomerPortalCMS.GeneratedModels.HomeFeaturedControls.GetFeature3VideoLink(this); }
		}

		///<summary>
		/// Feature 4 Button Link: Enter the link for the "Learn More" button if it should appear.
		///</summary>
		[ImplementPropertyType("feature4ButtonLink")]
		public Umbraco.Web.Models.RelatedLinks Feature4ButtonLink
		{
			get { return CustomerPortalCMS.GeneratedModels.HomeFeaturedControls.GetFeature4ButtonLink(this); }
		}

		///<summary>
		/// Feature 4 Direct Video Link: Choose the video to play in the popup
		///</summary>
		[ImplementPropertyType("feature4DirectVideoLink")]
		public Umbraco.Web.Models.RelatedLinks Feature4DirectVideoLink
		{
			get { return CustomerPortalCMS.GeneratedModels.HomeFeaturedControls.GetFeature4DirectVideoLink(this); }
		}

		///<summary>
		/// Feature 4 Label: Enter the text for feature 4.
		///</summary>
		[ImplementPropertyType("feature4Label")]
		public string Feature4Label
		{
			get { return CustomerPortalCMS.GeneratedModels.HomeFeaturedControls.GetFeature4Label(this); }
		}

		///<summary>
		/// Feature 4 Thumbnail: Choose the thumbnail image for feature 4
		///</summary>
		[ImplementPropertyType("feature4Thumbnail")]
		public IPublishedContent Feature4Thumbnail
		{
			get { return CustomerPortalCMS.GeneratedModels.HomeFeaturedControls.GetFeature4Thumbnail(this); }
		}

		///<summary>
		/// Feature 4 Video Link: If this should link to a list of videos enter the link here
		///</summary>
		[ImplementPropertyType("feature4VideoLink")]
		public Umbraco.Web.Models.RelatedLinks Feature4VideoLink
		{
			get { return CustomerPortalCMS.GeneratedModels.HomeFeaturedControls.GetFeature4VideoLink(this); }
		}

		///<summary>
		/// Meta Description: Best practice is to keep description under 150 characters
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription
		{
			get { return CustomerPortalCMS.GeneratedModels.SEocontrols.GetMetaDescription(this); }
		}

		///<summary>
		/// SEO Page Title: Overrides Title (from Page Title tab) and Name
		///</summary>
		[ImplementPropertyType("sEOPageTitle")]
		public string SEopageTitle
		{
			get { return CustomerPortalCMS.GeneratedModels.SEocontrols.GetSEopageTitle(this); }
		}
	}
}
