//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace CustomerPortalCMS.GeneratedModels
{
	// Mixin content Type 1274 with alias "homeConstructionControls"
	/// <summary>Home Construction Controls</summary>
	public partial interface IHomeConstructionControls : IPublishedContent
	{
		/// <summary>Construction Type Title</summary>
		string ConstructionTypeTitle { get; }

		/// <summary>Type 1</summary>
		string Type1 { get; }

		/// <summary>Type 1 Link</summary>
		Umbraco.Web.Models.RelatedLinks Type1Link { get; }

		/// <summary>Type 2</summary>
		string Type2 { get; }

		/// <summary>Type 2 Link</summary>
		Umbraco.Web.Models.RelatedLinks Type2Link { get; }

		/// <summary>Type 3</summary>
		string Type3 { get; }

		/// <summary>Type 3 Link</summary>
		Umbraco.Web.Models.RelatedLinks Type3Link { get; }
	}

	/// <summary>Home Construction Controls</summary>
	[PublishedContentModel("homeConstructionControls")]
	public partial class HomeConstructionControls : PublishedContentModel, IHomeConstructionControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "homeConstructionControls";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HomeConstructionControls(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HomeConstructionControls, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Construction Type Title
		///</summary>
		[ImplementPropertyType("constructionTypeTitle")]
		public string ConstructionTypeTitle
		{
			get { return GetConstructionTypeTitle(this); }
		}

		/// <summary>Static getter for Construction Type Title</summary>
		public static string GetConstructionTypeTitle(IHomeConstructionControls that) { return that.GetPropertyValue<string>("constructionTypeTitle"); }

		///<summary>
		/// Type 1: Enter the text for the link
		///</summary>
		[ImplementPropertyType("type1")]
		public string Type1
		{
			get { return GetType1(this); }
		}

		/// <summary>Static getter for Type 1</summary>
		public static string GetType1(IHomeConstructionControls that) { return that.GetPropertyValue<string>("type1"); }

		///<summary>
		/// Type 1 Link: Choose the page to link to
		///</summary>
		[ImplementPropertyType("type1Link")]
		public Umbraco.Web.Models.RelatedLinks Type1Link
		{
			get { return GetType1Link(this); }
		}

		/// <summary>Static getter for Type 1 Link</summary>
		public static Umbraco.Web.Models.RelatedLinks GetType1Link(IHomeConstructionControls that) { return that.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("type1Link"); }

		///<summary>
		/// Type 2: Enter the text for the link
		///</summary>
		[ImplementPropertyType("type2")]
		public string Type2
		{
			get { return GetType2(this); }
		}

		/// <summary>Static getter for Type 2</summary>
		public static string GetType2(IHomeConstructionControls that) { return that.GetPropertyValue<string>("type2"); }

		///<summary>
		/// Type 2 Link: Choose the page to link to
		///</summary>
		[ImplementPropertyType("type2Link")]
		public Umbraco.Web.Models.RelatedLinks Type2Link
		{
			get { return GetType2Link(this); }
		}

		/// <summary>Static getter for Type 2 Link</summary>
		public static Umbraco.Web.Models.RelatedLinks GetType2Link(IHomeConstructionControls that) { return that.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("type2Link"); }

		///<summary>
		/// Type 3: Enter the text for the link
		///</summary>
		[ImplementPropertyType("type3")]
		public string Type3
		{
			get { return GetType3(this); }
		}

		/// <summary>Static getter for Type 3</summary>
		public static string GetType3(IHomeConstructionControls that) { return that.GetPropertyValue<string>("type3"); }

		///<summary>
		/// Type 3 Link: Choose a page to link to
		///</summary>
		[ImplementPropertyType("type3Link")]
		public Umbraco.Web.Models.RelatedLinks Type3Link
		{
			get { return GetType3Link(this); }
		}

		/// <summary>Static getter for Type 3 Link</summary>
		public static Umbraco.Web.Models.RelatedLinks GetType3Link(IHomeConstructionControls that) { return that.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("type3Link"); }
	}
}
