//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace CustomerPortalCMS.GeneratedModels
{
	/// <summary>Installed Services Type</summary>
	[PublishedContentModel("installedServicesType")]
	public partial class InstalledServicesType : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "installedServicesType";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public InstalledServicesType(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<InstalledServicesType, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Active?: Unchecked if this Installed Service Type is no longer active.
		///</summary>
		[ImplementPropertyType("active")]
		public bool Active
		{
			get { return this.GetPropertyValue<bool>("active"); }
		}

		///<summary>
		/// Show In Location Search Filters: Check this box to have this service displayed among the search filters on the main Locations page
		///</summary>
		[ImplementPropertyType("showInLocationSearchFilters")]
		public bool ShowInLocationSearchFilters
		{
			get { return this.GetPropertyValue<bool>("showInLocationSearchFilters"); }
		}

		///<summary>
		/// Show On Install Services Page: Check this box id this service is to be shown on the Installation Services page.
		///</summary>
		[ImplementPropertyType("showOnInstallServicesPage")]
		public bool ShowOnInstallServicesPage
		{
			get { return this.GetPropertyValue<bool>("showOnInstallServicesPage"); }
		}

		///<summary>
		/// Show On Location Details Pages: check this box if this service is to be displayed on a particular Location's Details page (if the service is offered).
		///</summary>
		[ImplementPropertyType("showOnLocationDetailsPages")]
		public bool ShowOnLocationDetailsPages
		{
			get { return this.GetPropertyValue<bool>("showOnLocationDetailsPages"); }
		}

		///<summary>
		/// Service Image: Choose an image for this installed service
		///</summary>
		[ImplementPropertyType("typeImage")]
		public IPublishedContent TypeImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("typeImage"); }
		}

		///<summary>
		/// Service Name
		///</summary>
		[ImplementPropertyType("typeName")]
		public string TypeName
		{
			get { return this.GetPropertyValue<string>("typeName"); }
		}
	}
}
