//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace CustomerPortalCMS.GeneratedModels
{
	/// <summary>Jobs Document Parent Folder</summary>
	[PublishedContentModel("JobsDocumentParentFolder")]
	public partial class JobsDocumentParentFolder : PublishedContentModel, IJobsListControl
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "JobsDocumentParentFolder";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public JobsDocumentParentFolder(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<JobsDocumentParentFolder, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Job Description
		///</summary>
		[ImplementPropertyType("jobDescription")]
		public IHtmlString JobDescription
		{
			get { return CustomerPortalCMS.GeneratedModels.JobsListControl.GetJobDescription(this); }
		}

		///<summary>
		/// Job Image
		///</summary>
		[ImplementPropertyType("jobImage")]
		public Umbraco.Web.Models.ImageCropDataSet JobImage
		{
			get { return CustomerPortalCMS.GeneratedModels.JobsListControl.GetJobImage(this); }
		}

		///<summary>
		/// Job Image Caption
		///</summary>
		[ImplementPropertyType("jobImageCaption")]
		public string JobImageCaption
		{
			get { return CustomerPortalCMS.GeneratedModels.JobsListControl.GetJobImageCaption(this); }
		}

		///<summary>
		/// Job Link
		///</summary>
		[ImplementPropertyType("jobLink")]
		public Umbraco.Web.Models.RelatedLinks JobLink
		{
			get { return CustomerPortalCMS.GeneratedModels.JobsListControl.GetJobLink(this); }
		}

		///<summary>
		/// Job Title
		///</summary>
		[ImplementPropertyType("jobTitle")]
		public string JobTitle
		{
			get { return CustomerPortalCMS.GeneratedModels.JobsListControl.GetJobTitle(this); }
		}

		///<summary>
		/// Job Video Link
		///</summary>
		[ImplementPropertyType("jobVideoLink")]
		public Umbraco.Web.Models.RelatedLinks JobVideoLink
		{
			get { return CustomerPortalCMS.GeneratedModels.JobsListControl.GetJobVideoLink(this); }
		}
	}
}
