//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace CustomerPortalCMS.GeneratedModels
{
	// Mixin content Type 13092 with alias "jobsListControl"
	/// <summary>Jobs List Control</summary>
	public partial interface IJobsListControl : IPublishedContent
	{
		/// <summary>Job Description</summary>
		IHtmlString JobDescription { get; }

		/// <summary>Job Image</summary>
		Umbraco.Web.Models.ImageCropDataSet JobImage { get; }

		/// <summary>Job Image Caption</summary>
		string JobImageCaption { get; }

		/// <summary>Job Link</summary>
		Umbraco.Web.Models.RelatedLinks JobLink { get; }

		/// <summary>Job Title</summary>
		string JobTitle { get; }

		/// <summary>Job Video Link</summary>
		Umbraco.Web.Models.RelatedLinks JobVideoLink { get; }
	}

	/// <summary>Jobs List Control</summary>
	[PublishedContentModel("jobsListControl")]
	public partial class JobsListControl : PublishedContentModel, IJobsListControl
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "jobsListControl";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public JobsListControl(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<JobsListControl, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Job Description
		///</summary>
		[ImplementPropertyType("jobDescription")]
		public IHtmlString JobDescription
		{
			get { return GetJobDescription(this); }
		}

		/// <summary>Static getter for Job Description</summary>
		public static IHtmlString GetJobDescription(IJobsListControl that) { return that.GetPropertyValue<IHtmlString>("jobDescription"); }

		///<summary>
		/// Job Image
		///</summary>
		[ImplementPropertyType("jobImage")]
		public Umbraco.Web.Models.ImageCropDataSet JobImage
		{
			get { return GetJobImage(this); }
		}

		/// <summary>Static getter for Job Image</summary>
		public static Umbraco.Web.Models.ImageCropDataSet GetJobImage(IJobsListControl that) { return that.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("jobImage"); }

		///<summary>
		/// Job Image Caption
		///</summary>
		[ImplementPropertyType("jobImageCaption")]
		public string JobImageCaption
		{
			get { return GetJobImageCaption(this); }
		}

		/// <summary>Static getter for Job Image Caption</summary>
		public static string GetJobImageCaption(IJobsListControl that) { return that.GetPropertyValue<string>("jobImageCaption"); }

		///<summary>
		/// Job Link
		///</summary>
		[ImplementPropertyType("jobLink")]
		public Umbraco.Web.Models.RelatedLinks JobLink
		{
			get { return GetJobLink(this); }
		}

		/// <summary>Static getter for Job Link</summary>
		public static Umbraco.Web.Models.RelatedLinks GetJobLink(IJobsListControl that) { return that.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("jobLink"); }

		///<summary>
		/// Job Title
		///</summary>
		[ImplementPropertyType("jobTitle")]
		public string JobTitle
		{
			get { return GetJobTitle(this); }
		}

		/// <summary>Static getter for Job Title</summary>
		public static string GetJobTitle(IJobsListControl that) { return that.GetPropertyValue<string>("jobTitle"); }

		///<summary>
		/// Job Video Link
		///</summary>
		[ImplementPropertyType("jobVideoLink")]
		public Umbraco.Web.Models.RelatedLinks JobVideoLink
		{
			get { return GetJobVideoLink(this); }
		}

		/// <summary>Static getter for Job Video Link</summary>
		public static Umbraco.Web.Models.RelatedLinks GetJobVideoLink(IJobsListControl that) { return that.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("jobVideoLink"); }
	}
}
