//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace CustomerPortalCMS.GeneratedModels
{
	/// <summary>Location List Item</summary>
	[PublishedContentModel("locationListItem")]
	public partial class LocationListItem : PublishedContentModel, ITopNavigationControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "locationListItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public LocationListItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<LocationListItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Acoustical Ceilings
		///</summary>
		[ImplementPropertyType("acousticalCeilings")]
		public IEnumerable<IPublishedContent> AcousticalCeilings
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("acousticalCeilings"); }
		}

		///<summary>
		/// Active: Unchecked if this store is no longer active.
		///</summary>
		[ImplementPropertyType("active")]
		public bool Active
		{
			get { return this.GetPropertyValue<bool>("active"); }
		}

		///<summary>
		/// Additional Link
		///</summary>
		[ImplementPropertyType("additionalLink")]
		public string AdditionalLink
		{
			get { return this.GetPropertyValue<string>("additionalLink"); }
		}

		///<summary>
		/// Address1
		///</summary>
		[ImplementPropertyType("address1")]
		public string Address1
		{
			get { return this.GetPropertyValue<string>("address1"); }
		}

		///<summary>
		/// Address2
		///</summary>
		[ImplementPropertyType("address2")]
		public string Address2
		{
			get { return this.GetPropertyValue<string>("address2"); }
		}

		///<summary>
		/// Adhesives & Sealants
		///</summary>
		[ImplementPropertyType("adhesivesSealants")]
		public IEnumerable<IPublishedContent> AdhesivesSealants
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("adhesivesSealants"); }
		}

		///<summary>
		/// Brick
		///</summary>
		[ImplementPropertyType("brick")]
		public IEnumerable<IPublishedContent> Brick
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("brick"); }
		}

		///<summary>
		/// Cabinets
		///</summary>
		[ImplementPropertyType("cabinets")]
		public IEnumerable<IPublishedContent> Cabinets
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("cabinets"); }
		}

		///<summary>
		/// City
		///</summary>
		[ImplementPropertyType("city")]
		public string City
		{
			get { return this.GetPropertyValue<string>("city"); }
		}

		///<summary>
		/// Civil
		///</summary>
		[ImplementPropertyType("civil")]
		public IEnumerable<IPublishedContent> Civil
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("civil"); }
		}

		///<summary>
		/// Coatings
		///</summary>
		[ImplementPropertyType("coatings")]
		public IEnumerable<IPublishedContent> Coatings
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("coatings"); }
		}

		///<summary>
		/// Columns
		///</summary>
		[ImplementPropertyType("columns")]
		public IEnumerable<IPublishedContent> Columns
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("columns"); }
		}

		///<summary>
		/// Concrete & Concrete Accessories
		///</summary>
		[ImplementPropertyType("concrete")]
		public IEnumerable<IPublishedContent> Concrete
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("concrete"); }
		}

		///<summary>
		/// Connectors
		///</summary>
		[ImplementPropertyType("connectors")]
		public IEnumerable<IPublishedContent> Connectors
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("connectors"); }
		}

		///<summary>
		/// Contact Manager
		///</summary>
		[ImplementPropertyType("contactManager")]
		public string ContactManager
		{
			get { return this.GetPropertyValue<string>("contactManager"); }
		}

		///<summary>
		/// Cultured Stone
		///</summary>
		[ImplementPropertyType("culturedStone")]
		public IEnumerable<IPublishedContent> CulturedStone
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("culturedStone"); }
		}

		///<summary>
		/// Decking
		///</summary>
		[ImplementPropertyType("decking")]
		public IEnumerable<IPublishedContent> Decking
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("decking"); }
		}

		///<summary>
		/// Doors
		///</summary>
		[ImplementPropertyType("doors")]
		public IEnumerable<IPublishedContent> Doors
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("doors"); }
		}

		///<summary>
		/// Drywall
		///</summary>
		[ImplementPropertyType("drywall")]
		public IEnumerable<IPublishedContent> Drywall
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("drywall"); }
		}

		///<summary>
		/// Email
		///</summary>
		[ImplementPropertyType("email")]
		public string Email
		{
			get { return this.GetPropertyValue<string>("email"); }
		}

		///<summary>
		/// Engineered Wood Products
		///</summary>
		[ImplementPropertyType("engineeredWoodProducts")]
		public IEnumerable<IPublishedContent> EngineeredWoodProducts
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("engineeredWoodProducts"); }
		}

		///<summary>
		/// Fax
		///</summary>
		[ImplementPropertyType("fax")]
		public string Fax
		{
			get { return this.GetPropertyValue<string>("fax"); }
		}

		///<summary>
		/// Fireplaces
		///</summary>
		[ImplementPropertyType("fireplaces")]
		public IEnumerable<IPublishedContent> Fireplaces
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("fireplaces"); }
		}

		///<summary>
		/// Flooring
		///</summary>
		[ImplementPropertyType("flooring")]
		public IEnumerable<IPublishedContent> Flooring
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("flooring"); }
		}

		///<summary>
		/// Garage Doors
		///</summary>
		[ImplementPropertyType("garageDoors")]
		public IEnumerable<IPublishedContent> GarageDoors
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("garageDoors"); }
		}

		///<summary>
		/// Hardware
		///</summary>
		[ImplementPropertyType("hardware")]
		public IEnumerable<IPublishedContent> Hardware
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("hardware"); }
		}

		///<summary>
		/// Hours M-F: ie. 10am - 8pm
		///</summary>
		[ImplementPropertyType("hoursMF")]
		public string HoursMF
		{
			get { return this.GetPropertyValue<string>("hoursMF"); }
		}

		///<summary>
		/// Hours Saturday: ie. 9am - 1pm, or Closed
		///</summary>
		[ImplementPropertyType("hoursSaturday")]
		public string HoursSaturday
		{
			get { return this.GetPropertyValue<string>("hoursSaturday"); }
		}

		///<summary>
		/// Hours Sunday: ie. 9am - 1pm, or Closed
		///</summary>
		[ImplementPropertyType("hoursSunday")]
		public string HoursSunday
		{
			get { return this.GetPropertyValue<string>("hoursSunday"); }
		}

		///<summary>
		/// House Wrap
		///</summary>
		[ImplementPropertyType("houseWrap")]
		public IEnumerable<IPublishedContent> HouseWrap
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("houseWrap"); }
		}

		///<summary>
		/// ICF
		///</summary>
		[ImplementPropertyType("iCF")]
		public IEnumerable<IPublishedContent> ICF
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("iCF"); }
		}

		///<summary>
		/// Installed Services Picker
		///</summary>
		[ImplementPropertyType("installedServicesPicker")]
		public IEnumerable<IPublishedContent> InstalledServicesPicker
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("installedServicesPicker"); }
		}

		///<summary>
		/// Insulation
		///</summary>
		[ImplementPropertyType("insulation")]
		public IEnumerable<IPublishedContent> Insulation
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("insulation"); }
		}

		///<summary>
		/// Interior Trim & Mouldings
		///</summary>
		[ImplementPropertyType("interiorTrimMouldings")]
		public IEnumerable<IPublishedContent> InteriorTrimMouldings
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("interiorTrimMouldings"); }
		}

		///<summary>
		/// Large Image: Select a location image.
		///</summary>
		[ImplementPropertyType("largeImage")]
		public IPublishedContent LargeImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("largeImage"); }
		}

		///<summary>
		/// Latitude
		///</summary>
		[ImplementPropertyType("latitude")]
		public string Latitude
		{
			get { return this.GetPropertyValue<string>("latitude"); }
		}

		///<summary>
		/// Location Description
		///</summary>
		[ImplementPropertyType("locationDescription")]
		public IHtmlString LocationDescription
		{
			get { return this.GetPropertyValue<IHtmlString>("locationDescription"); }
		}

		///<summary>
		/// Location Manager
		///</summary>
		[ImplementPropertyType("locationManager")]
		public string LocationManager
		{
			get { return this.GetPropertyValue<string>("locationManager"); }
		}

		///<summary>
		/// Location Name
		///</summary>
		[ImplementPropertyType("locationName")]
		public string LocationName
		{
			get { return this.GetPropertyValue<string>("locationName"); }
		}

		///<summary>
		/// Logo Image: Select a logo for this location
		///</summary>
		[ImplementPropertyType("logoImage")]
		public IPublishedContent LogoImage
		{
			get { return this.GetPropertyValue<IPublishedContent>("logoImage"); }
		}

		///<summary>
		/// Logo Image Title
		///</summary>
		[ImplementPropertyType("logoImageTitle")]
		public string LogoImageTitle
		{
			get { return this.GetPropertyValue<string>("logoImageTitle"); }
		}

		///<summary>
		/// Longitude
		///</summary>
		[ImplementPropertyType("longitude")]
		public string Longitude
		{
			get { return this.GetPropertyValue<string>("longitude"); }
		}

		///<summary>
		/// Lumber & Treated Wood
		///</summary>
		[ImplementPropertyType("lumberTreatedWood")]
		public IEnumerable<IPublishedContent> LumberTreatedWood
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("lumberTreatedWood"); }
		}

		///<summary>
		/// LVL Wood Beams
		///</summary>
		[ImplementPropertyType("lvlWoodBeams")]
		public IEnumerable<IPublishedContent> LvlWoodBeams
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("lvlWoodBeams"); }
		}

		///<summary>
		/// Main Phone
		///</summary>
		[ImplementPropertyType("mainPhone")]
		public string MainPhone
		{
			get { return this.GetPropertyValue<string>("mainPhone"); }
		}

		///<summary>
		/// Manager Name
		///</summary>
		[ImplementPropertyType("managerName")]
		public string ManagerName
		{
			get { return this.GetPropertyValue<string>("managerName"); }
		}

		///<summary>
		/// Misc Products
		///</summary>
		[ImplementPropertyType("miscProducts")]
		public IEnumerable<IPublishedContent> MiscProducts
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("miscProducts"); }
		}

		///<summary>
		/// Operation
		///</summary>
		[ImplementPropertyType("operation")]
		public string Operation
		{
			get { return this.GetPropertyValue<string>("operation"); }
		}

		///<summary>
		/// PVC
		///</summary>
		[ImplementPropertyType("pvc")]
		public IEnumerable<IPublishedContent> Pvc
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("pvc"); }
		}

		///<summary>
		/// Railings
		///</summary>
		[ImplementPropertyType("railings")]
		public IEnumerable<IPublishedContent> Railings
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("railings"); }
		}

		///<summary>
		/// Road Markings
		///</summary>
		[ImplementPropertyType("roadMarkings")]
		public IEnumerable<IPublishedContent> RoadMarkings
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("roadMarkings"); }
		}

		///<summary>
		/// Roofing
		///</summary>
		[ImplementPropertyType("roofing")]
		public IEnumerable<IPublishedContent> Roofing
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("roofing"); }
		}

		///<summary>
		/// Sales Manager
		///</summary>
		[ImplementPropertyType("salesManager")]
		public string SalesManager
		{
			get { return this.GetPropertyValue<string>("salesManager"); }
		}

		///<summary>
		/// Second Phone
		///</summary>
		[ImplementPropertyType("secondPhone")]
		public string SecondPhone
		{
			get { return this.GetPropertyValue<string>("secondPhone"); }
		}

		///<summary>
		/// Sheathing
		///</summary>
		[ImplementPropertyType("sheathing")]
		public IEnumerable<IPublishedContent> Sheathing
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("sheathing"); }
		}

		///<summary>
		/// Shingles
		///</summary>
		[ImplementPropertyType("shingles")]
		public IEnumerable<IPublishedContent> Shingles
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("shingles"); }
		}

		///<summary>
		/// Shutters
		///</summary>
		[ImplementPropertyType("shutters")]
		public IEnumerable<IPublishedContent> Shutters
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("shutters"); }
		}

		///<summary>
		/// Siding
		///</summary>
		[ImplementPropertyType("siding")]
		public IEnumerable<IPublishedContent> Siding
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("siding"); }
		}

		///<summary>
		/// Stairs
		///</summary>
		[ImplementPropertyType("stairs")]
		public IEnumerable<IPublishedContent> Stairs
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("stairs"); }
		}

		///<summary>
		/// State
		///</summary>
		[ImplementPropertyType("state")]
		public string State
		{
			get { return this.GetPropertyValue<string>("state"); }
		}

		///<summary>
		/// Steel
		///</summary>
		[ImplementPropertyType("steel")]
		public IEnumerable<IPublishedContent> Steel
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("steel"); }
		}

		///<summary>
		/// Steel Trusses
		///</summary>
		[ImplementPropertyType("steelTrusses")]
		public IEnumerable<IPublishedContent> SteelTrusses
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("steelTrusses"); }
		}

		///<summary>
		/// Store Color
		///</summary>
		[ImplementPropertyType("storeColor")]
		public object StoreColor
		{
			get { return this.GetPropertyValue("storeColor"); }
		}

		///<summary>
		/// Store Icon Type
		///</summary>
		[ImplementPropertyType("storeIconType")]
		public string StoreIconType
		{
			get { return this.GetPropertyValue<string>("storeIconType"); }
		}

		///<summary>
		/// Stucco
		///</summary>
		[ImplementPropertyType("stucco")]
		public IEnumerable<IPublishedContent> Stucco
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("stucco"); }
		}

		///<summary>
		/// Tools and Accessories
		///</summary>
		[ImplementPropertyType("toolsAndAccessories")]
		public IEnumerable<IPublishedContent> ToolsAndAccessories
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("toolsAndAccessories"); }
		}

		///<summary>
		/// Wall Panels
		///</summary>
		[ImplementPropertyType("wallPanel")]
		public IEnumerable<IPublishedContent> WallPanel
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("wallPanel"); }
		}

		///<summary>
		/// Windows
		///</summary>
		[ImplementPropertyType("windows")]
		public IEnumerable<IPublishedContent> Windows
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("windows"); }
		}

		///<summary>
		/// Wood Trusses
		///</summary>
		[ImplementPropertyType("woodTrusses")]
		public IEnumerable<IPublishedContent> WoodTrusses
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("woodTrusses"); }
		}

		///<summary>
		/// ZipCode
		///</summary>
		[ImplementPropertyType("zipCode")]
		public string ZipCode
		{
			get { return this.GetPropertyValue<string>("zipCode"); }
		}

		///<summary>
		/// Hide If No Customer Selected?  (CP Sales Node Only!): (This is being replaced with Hide from navigation) Click this if you do not want this page to appear in the top nav
		///</summary>
		[ImplementPropertyType("excludeFromTopNavigation")]
		public bool ExcludeFromTopNavigation
		{
			get { return CustomerPortalCMS.GeneratedModels.TopNavigationControls.GetExcludeFromTopNavigation(this); }
		}

		///<summary>
		/// Hide from navigation: When checked, page will be hidden from navigation but still accessible by URL.
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return CustomerPortalCMS.GeneratedModels.TopNavigationControls.GetUmbracoNaviHide(this); }
		}
	}
}
