//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace CustomerPortalCMS.GeneratedModels
{
	/// <summary>Market Data Item</summary>
	[PublishedContentModel("marketDataItem")]
	public partial class MarketDataItem : PublishedContentModel, ICpDashboardPreferences
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "marketDataItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public MarketDataItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<MarketDataItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Market Full Name: The market's full name.
		///</summary>
		[ImplementPropertyType("marketFullName")]
		public string MarketFullName
		{
			get { return this.GetPropertyValue<string>("marketFullName"); }
		}

		///<summary>
		/// Invoice Tab Visible?: Is the invoices tab visible?
		///</summary>
		[ImplementPropertyType("cpDashboardIsInvoiceTabVisible")]
		public bool CpDashboardIsInvoiceTabVisible
		{
			get { return CustomerPortalCMS.GeneratedModels.CpDashboardPreferences.GetCpDashboardIsInvoiceTabVisible(this); }
		}

		///<summary>
		/// Pick Tickets Tab Visible?: Is the Pick Ticket tab visible?
		///</summary>
		[ImplementPropertyType("cpDashboardIsPickTicketsTabVisible")]
		public bool CpDashboardIsPickTicketsTabVisible
		{
			get { return CustomerPortalCMS.GeneratedModels.CpDashboardPreferences.GetCpDashboardIsPickTicketsTabVisible(this); }
		}

		///<summary>
		/// Quotes Tab Visible?: Is the Quotes tab visible?
		///</summary>
		[ImplementPropertyType("cpDashboardIsQuotesTabVisible")]
		public bool CpDashboardIsQuotesTabVisible
		{
			get { return CustomerPortalCMS.GeneratedModels.CpDashboardPreferences.GetCpDashboardIsQuotesTabVisible(this); }
		}

		///<summary>
		/// Sales Order Tab Visible?: Is the Sales Order tab visible?
		///</summary>
		[ImplementPropertyType("cpDashboardIsSalesOrderTabVisible")]
		public bool CpDashboardIsSalesOrderTabVisible
		{
			get { return CustomerPortalCMS.GeneratedModels.CpDashboardPreferences.GetCpDashboardIsSalesOrderTabVisible(this); }
		}

		///<summary>
		/// Statement Tab Visible?: Is the Statement tab visible?
		///</summary>
		[ImplementPropertyType("cpDashboardIsStatementTabVisible")]
		public bool CpDashboardIsStatementTabVisible
		{
			get { return CustomerPortalCMS.GeneratedModels.CpDashboardPreferences.GetCpDashboardIsStatementTabVisible(this); }
		}
	}
}
