//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace CustomerPortalCMS.GeneratedModels
{
	/// <summary>Member</summary>
	[PublishedContentModel("Member")]
	public partial class Member : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Member";
		public new const PublishedItemType ModelItemType = PublishedItemType.Member;
#pragma warning restore 0109

		public Member(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Member, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Customer Name: This should match arname column in online. Should be set when customer registers
		///</summary>
		[ImplementPropertyType("customerName")]
		public string CustomerName
		{
			get { return this.GetPropertyValue<string>("customerName"); }
		}

		///<summary>
		/// Customer Number: arnum or arnum2 from Online. Set on Register
		///</summary>
		[ImplementPropertyType("customerNumber")]
		public string CustomerNumber
		{
			get { return this.GetPropertyValue<string>("customerNumber"); }
		}

		///<summary>
		/// Date TOS Accepted: The date the customer accepted the terms of service agreement.
		///</summary>
		[ImplementPropertyType("dateTOSAccepted")]
		public DateTime DateTosaccepted
		{
			get { return this.GetPropertyValue<DateTime>("dateTOSAccepted"); }
		}

		///<summary>
		/// Employee ID: Employee Number
		///</summary>
		[ImplementPropertyType("employeeID")]
		public string EmployeeID
		{
			get { return this.GetPropertyValue<string>("employeeID"); }
		}

		///<summary>
		/// First Name: Member's given name.
		///</summary>
		[ImplementPropertyType("firstName")]
		public string FirstName
		{
			get { return this.GetPropertyValue<string>("firstName"); }
		}

		///<summary>
		/// Invoice Amount: The invoice $ amount entered during the self-registration process.
		///</summary>
		[ImplementPropertyType("invoiceAmount")]
		public string InvoiceAmount
		{
			get { return this.GetPropertyValue<string>("invoiceAmount"); }
		}

		///<summary>
		/// Invoice Number: The invoice number used during the self-registration process.
		///</summary>
		[ImplementPropertyType("invoiceNumber")]
		public string InvoiceNumber
		{
			get { return this.GetPropertyValue<string>("invoiceNumber"); }
		}

		///<summary>
		/// Customer Admin
		///</summary>
		[ImplementPropertyType("IsCustomerAdmin")]
		public bool IsCustomerAdmin
		{
			get { return this.GetPropertyValue<bool>("IsCustomerAdmin"); }
		}

		///<summary>
		/// Is Email Validated: Has the email address been verified via email link back?
		///</summary>
		[ImplementPropertyType("isEmailValidated")]
		public bool IsEmailValidated
		{
			get { return this.GetPropertyValue<bool>("isEmailValidated"); }
		}

		///<summary>
		/// Last Name: Member's last name.
		///</summary>
		[ImplementPropertyType("lastName")]
		public string LastName
		{
			get { return this.GetPropertyValue<string>("lastName"); }
		}

		///<summary>
		/// Is Approved
		///</summary>
		[ImplementPropertyType("umbracoMemberApproved")]
		public bool UmbracoMemberApproved
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberApproved"); }
		}

		///<summary>
		/// Comments
		///</summary>
		[ImplementPropertyType("umbracoMemberComments")]
		public string UmbracoMemberComments
		{
			get { return this.GetPropertyValue<string>("umbracoMemberComments"); }
		}

		///<summary>
		/// Failed Password Attempts
		///</summary>
		[ImplementPropertyType("umbracoMemberFailedPasswordAttempts")]
		public string UmbracoMemberFailedPasswordAttempts
		{
			get { return this.GetPropertyValue<string>("umbracoMemberFailedPasswordAttempts"); }
		}

		///<summary>
		/// Last Lockout Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLockoutDate")]
		public string UmbracoMemberLastLockoutDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLockoutDate"); }
		}

		///<summary>
		/// Last Login Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLogin")]
		public string UmbracoMemberLastLogin
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLogin"); }
		}

		///<summary>
		/// Last Password Change Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastPasswordChangeDate")]
		public string UmbracoMemberLastPasswordChangeDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastPasswordChangeDate"); }
		}

		///<summary>
		/// Is Locked Out
		///</summary>
		[ImplementPropertyType("umbracoMemberLockedOut")]
		public bool UmbracoMemberLockedOut
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberLockedOut"); }
		}

		///<summary>
		/// Password Answer
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalAnswer")]
		public string UmbracoMemberPasswordRetrievalAnswer
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalAnswer"); }
		}

		///<summary>
		/// Password Question
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalQuestion")]
		public string UmbracoMemberPasswordRetrievalQuestion
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalQuestion"); }
		}
	}
}
