//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace CustomerPortalCMS.GeneratedModels
{
	// Mixin content Type 13074 with alias "pageHeaderControl1"
	/// <summary>Page Header Control-Small Header</summary>
	public partial interface IPageHeaderControl1 : IPublishedContent
	{
		/// <summary>Content</summary>
		IHtmlString Content { get; }

		/// <summary>Header Background Image</summary>
		Umbraco.Web.Models.ImageCropDataSet HeaderBackgroundImage { get; }

		/// <summary>Page Title</summary>
		string PageTitle { get; }
	}

	/// <summary>Page Header Control-Small Header</summary>
	[PublishedContentModel("pageHeaderControl1")]
	public partial class PageHeaderControl1 : PublishedContentModel, IPageHeaderControl1
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "pageHeaderControl1";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public PageHeaderControl1(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<PageHeaderControl1, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Content
		///</summary>
		[ImplementPropertyType("content")]
		public IHtmlString Content
		{
			get { return GetContent(this); }
		}

		/// <summary>Static getter for Content</summary>
		public static IHtmlString GetContent(IPageHeaderControl1 that) { return that.GetPropertyValue<IHtmlString>("content"); }

		///<summary>
		/// Header Background Image
		///</summary>
		[ImplementPropertyType("headerBackgroundImage")]
		public Umbraco.Web.Models.ImageCropDataSet HeaderBackgroundImage
		{
			get { return GetHeaderBackgroundImage(this); }
		}

		/// <summary>Static getter for Header Background Image</summary>
		public static Umbraco.Web.Models.ImageCropDataSet GetHeaderBackgroundImage(IPageHeaderControl1 that) { return that.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("headerBackgroundImage"); }

		///<summary>
		/// Page Title
		///</summary>
		[ImplementPropertyType("pageTitle")]
		public string PageTitle
		{
			get { return GetPageTitle(this); }
		}

		/// <summary>Static getter for Page Title</summary>
		public static string GetPageTitle(IPageHeaderControl1 that) { return that.GetPropertyValue<string>("pageTitle"); }
	}
}
