//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace CustomerPortalCMS.GeneratedModels
{
	// Mixin content Type 1281 with alias "pageTitle"
	/// <summary>Page Title Controls</summary>
	public partial interface IPageTitle : IPublishedContent
	{
		/// <summary>Header Image</summary>
		IPublishedContent HeaderImage { get; }

		/// <summary>Title</summary>
		string Title { get; }
	}

	/// <summary>Page Title Controls</summary>
	[PublishedContentModel("pageTitle")]
	public partial class PageTitle : PublishedContentModel, IPageTitle
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "pageTitle";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public PageTitle(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<PageTitle, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Header Image: Choose the banner image for this page
		///</summary>
		[ImplementPropertyType("headerImage")]
		public IPublishedContent HeaderImage
		{
			get { return GetHeaderImage(this); }
		}

		/// <summary>Static getter for Header Image</summary>
		public static IPublishedContent GetHeaderImage(IPageTitle that) { return that.GetPropertyValue<IPublishedContent>("headerImage"); }

		///<summary>
		/// Title: Enter the Page Title - overrides page Name
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return GetTitle(this); }
		}

		/// <summary>Static getter for Title</summary>
		public static string GetTitle(IPageTitle that) { return that.GetPropertyValue<string>("title"); }
	}
}
