//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace CustomerPortalCMS.GeneratedModels
{
	// Mixin content Type 5017 with alias "sEOControls"
	/// <summary>SEO Controls</summary>
	public partial interface ISEocontrols : IPublishedContent
	{
		/// <summary>Meta Description</summary>
		string MetaDescription { get; }

		/// <summary>SEO Page Title</summary>
		string SEopageTitle { get; }
	}

	/// <summary>SEO Controls</summary>
	[PublishedContentModel("sEOControls")]
	public partial class SEocontrols : PublishedContentModel, ISEocontrols
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "sEOControls";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SEocontrols(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SEocontrols, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Meta Description: Best practice is to keep description under 150 characters
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription
		{
			get { return GetMetaDescription(this); }
		}

		/// <summary>Static getter for Meta Description</summary>
		public static string GetMetaDescription(ISEocontrols that) { return that.GetPropertyValue<string>("metaDescription"); }

		///<summary>
		/// SEO Page Title: Overrides Title (from Page Title tab) and Name
		///</summary>
		[ImplementPropertyType("sEOPageTitle")]
		public string SEopageTitle
		{
			get { return GetSEopageTitle(this); }
		}

		/// <summary>Static getter for SEO Page Title</summary>
		public static string GetSEopageTitle(ISEocontrols that) { return that.GetPropertyValue<string>("sEOPageTitle"); }
	}
}
