//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace CustomerPortalCMS.GeneratedModels
{
	/// <summary>Support</summary>
	[PublishedContentModel("support")]
	public partial class Support : PublishedContentModel, IBFscontactControls, IPageInfoControls, ITopNavigationControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "support";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Support(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Support, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Support Email
		///</summary>
		[ImplementPropertyType("supportEmail")]
		public string SupportEmail
		{
			get { return CustomerPortalCMS.GeneratedModels.BFscontactControls.GetSupportEmail(this); }
		}

		///<summary>
		/// Support Hours M-F
		///</summary>
		[ImplementPropertyType("supportHoursMF")]
		public string SupportHoursMF
		{
			get { return CustomerPortalCMS.GeneratedModels.BFscontactControls.GetSupportHoursMF(this); }
		}

		///<summary>
		/// Support Hours Sat
		///</summary>
		[ImplementPropertyType("supportHoursSat")]
		public string SupportHoursSat
		{
			get { return CustomerPortalCMS.GeneratedModels.BFscontactControls.GetSupportHoursSat(this); }
		}

		///<summary>
		/// Support Hours Sun
		///</summary>
		[ImplementPropertyType("supportHoursSun")]
		public string SupportHoursSun
		{
			get { return CustomerPortalCMS.GeneratedModels.BFscontactControls.GetSupportHoursSun(this); }
		}

		///<summary>
		/// Support Phone
		///</summary>
		[ImplementPropertyType("supportPhone")]
		public string SupportPhone
		{
			get { return CustomerPortalCMS.GeneratedModels.BFscontactControls.GetSupportPhone(this); }
		}

		///<summary>
		/// Is Impersonation Allowed: Indicates whether this page allows for impersonation, or not.
		///</summary>
		[ImplementPropertyType("isImpersonationAllowed")]
		public bool IsImpersonationAllowed
		{
			get { return CustomerPortalCMS.GeneratedModels.PageInfoControls.GetIsImpersonationAllowed(this); }
		}

		///<summary>
		/// Page Title: Enter the page title to be used, if left blank the page will be used
		///</summary>
		[ImplementPropertyType("pageTitle")]
		public string PageTitle
		{
			get { return CustomerPortalCMS.GeneratedModels.PageInfoControls.GetPageTitle(this); }
		}

		///<summary>
		/// Hide If No Customer Selected?  (CP Sales Node Only!): (This is being replaced with Hide from navigation) Click this if you do not want this page to appear in the top nav
		///</summary>
		[ImplementPropertyType("excludeFromTopNavigation")]
		public bool ExcludeFromTopNavigation
		{
			get { return CustomerPortalCMS.GeneratedModels.TopNavigationControls.GetExcludeFromTopNavigation(this); }
		}

		///<summary>
		/// Hide from navigation: When checked, page will be hidden from navigation but still accessible by URL.
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return CustomerPortalCMS.GeneratedModels.TopNavigationControls.GetUmbracoNaviHide(this); }
		}
	}
}
