//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace CustomerPortalCMS.GeneratedModels
{
	/// <summary>Video List Item</summary>
	[PublishedContentModel("videoListItem")]
	public partial class VideoListItem : PublishedContentModel, ITopNavigationControls
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "videoListItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public VideoListItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<VideoListItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Sort Index: oldest have lowest index
		///</summary>
		[ImplementPropertyType("sortIndex")]
		public int SortIndex
		{
			get { return this.GetPropertyValue<int>("sortIndex"); }
		}

		///<summary>
		/// Video Link Label
		///</summary>
		[ImplementPropertyType("videoLinkLabel")]
		public string VideoLinkLabel
		{
			get { return this.GetPropertyValue<string>("videoLinkLabel"); }
		}

		///<summary>
		/// Video Link Thumbnail
		///</summary>
		[ImplementPropertyType("videoLinkThumbnail")]
		public IPublishedContent VideoLinkThumbnail
		{
			get { return this.GetPropertyValue<IPublishedContent>("videoLinkThumbnail"); }
		}

		///<summary>
		/// Video Link URL
		///</summary>
		[ImplementPropertyType("videoLinkURL")]
		public Umbraco.Web.Models.RelatedLinks VideoLinkUrl
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.RelatedLinks>("videoLinkURL"); }
		}

		///<summary>
		/// Hide If No Customer Selected?  (CP Sales Node Only!): (This is being replaced with Hide from navigation) Click this if you do not want this page to appear in the top nav
		///</summary>
		[ImplementPropertyType("excludeFromTopNavigation")]
		public bool ExcludeFromTopNavigation
		{
			get { return CustomerPortalCMS.GeneratedModels.TopNavigationControls.GetExcludeFromTopNavigation(this); }
		}

		///<summary>
		/// Hide from navigation: When checked, page will be hidden from navigation but still accessible by URL.
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return CustomerPortalCMS.GeneratedModels.TopNavigationControls.GetUmbracoNaviHide(this); }
		}
	}
}
